### PR TITLE
`Navigation` color updates

### PR DESCRIPTION
**Pull request by sophschneider**
Fixes https://github.com/Shopify/polaris/issues/10358

### CODE REVIEW

**Review by lgriffee — APPROVED** [review]

**Comment by laurkim** [comment]
Not sure if this is an issue, but selected nav item looks like it's using `--p-color-bg-surface-selected`. I know the issue says to replace `--p-color-bg-app-selected` but I'm wondering if `--p-color-bg-surface-selected` just for this case needs to be updated to `--p-color-nav-surface-selected` for selected items so it matches the Figma screenshot on the issue.

29-39-wcw2y-9t40c

**Comment by aveline** [comment]
I was wondering the same thing as @laurkim and also given that the color value for `--p-color-bg-surface-selected` was update in https://github.com/Shopify/polaris/pull/10755 I think it's worth merging in the latest to get that change in with this work and see how it looks.

**Review by aveline — APPROVED** [review]

**Comment by sophschneider** [comment]
@laurkim I updated that token, thanks for catching it!!

**Review by laurkim — APPROVED** [review]
Nice 💯 🌟

**Comment by sophschneider** [comment]
@sarahill I'm going to merge this PR, https://github.com/Shopify/polaris/pull/10775 and https://github.com/Shopify/polaris/pull/10781 to unblock migrations, but if you see any issues I can update in a forward fix!

**Pull request merged**
