### PR TITLE
[ExceptionList] Fix collapsed exception list when description is undefined

### PR DESCRIPTION
**Pull request by jim-chou-shopify**
### WHY are these changes introduced?
Fixes https://github.com/Shopify/marketing-integrations/issues/576.
`ExceptionList` breaks the layout when there is an icon and description is undefined and has a sibling element. 
`ExceptionList` renders icon with absolute position and when there is no message the container has no height.
[DEMO of the problem](https://codesandbox.io/s/zealous-ritchie-s9261)

### WHAT is this pull request doing?
Apply `min-height: rem(20px)` to `ul` container element.
The min container height is base on the [icon height](https://github.com/Shopify/polaris-react/blob/02c2fd3a6f7fc3680b67eae5986a2e517ccdf085/src/components/ExceptionList/ExceptionList.scss#L27).

**Before**
Screen Shot 2020-03-19 at 3 52 32 PM
**After**
Screen Shot 2020-03-19 at 3 52 20 PM

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}

```

</details>

### 🎩 checklist

* [x] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

### CODE REVIEW

**Comment by BPScott** [comment]
Setting heights on containing elements always feel pretty janky to me. I'd  rather  try and work out some way that the line that the icon is on has some kind of height and it all flows from there. Otherwise things will get weird if users resize their text sizes.


I've not poked about with this but can we make it so the Icon is no longer absolutely positioned, (inline-block perhaps?) that might help give that line some intrinsic height

**Comment by jim-chou-shopify** [comment]
> Setting heights on containing elements always feel pretty janky to me. I'd rather try and work out some way that the line that the icon is on has some kind of height and it all flows from there. Otherwise things will get weird if users resize their text sizes.
> 
> I've not poked about with this but can we make it so the Icon is no longer absolutely positioned, (inline-block perhaps?) that might help give that line some intrinsic height

Regardless of the font size, the icon will probably not change height. 
Using the min height of the icon sort of works the same as making icon not absolute positioned.
Im not sure why icon need to be absolute positioned neither. Maybe worth a try.

**Comment by AndrewMusgrave** [comment]
> Regardless of the font size, the icon will probably not change height.
Using the min height of the icon sort of works the same as making icon not absolute positioned.
Im not sure why icon need to be absolute positioned neither. Maybe worth a try.

👋 Let us know if you're going to take a look. If not this should be good for a review!

**Comment by jim-chou-shopify** [comment]
> > Regardless of the font size, the icon will probably not change height.
> > Using the min height of the icon sort of works the same as making icon not absolute positioned.
> > Im not sure why icon need to be absolute positioned neither. Maybe worth a try.
> 
> 👋 Let us know if you're going to take a look. If not this should be good for a review!

Hey @BPScott @AndrewMusgrave,
I don't think I have time to look into refactoring the component to use relative position.
Do you think the proposed change in the PR is worth reviewing?

**Comment by BPScott** [comment]
Removing my review request as I'm moving off the polaris team

**Comment by alex-page** [comment]
@jim-chou-shopify is this still an issue?

**Pull request closed without merging**
