### PR TITLE
Remove scripts/profiler.js

### PR DESCRIPTION
**Pull request by alex-page**
### WHY are these changes introduced?

I am suggesting to remove the `scripts/profiler.js` as I have observed that it is:

- No longer used on the coverage site
- Adds puppeteer and chromium
- Has data that is rarely used or referenced
- It can be easily added back if necessary

### WHAT is this pull request doing?

Removes the `scripts/profiler.js` and dependencies

### CODE REVIEW

**Comment by gwyneplaine** [comment]
Am all for removing the profiler script, though I don't think we should be removing the ReactPerformanceProfiler add-on, since that's fairly useful in day to day dev and removing it wouldn't be a bundle size or performance win the same way removing the profiler script would be

Otherwise LGTM

**Review by gwyneplaine — APPROVED** [review]

**Review by jesstelford — COMMENTED** [review]
I've used this very script [just last (work) week](https://github.com/Shopify/polaris-internal/issues/1153#issuecomment-1829813514)!

It's super useful for testing the perf of components with something like this (horrific) bash script:

```
❯ yarn workspace @shopify/polaris dev &
❯ COUNT=10; (echo '['; for i in `seq 1 $COUNT`; do node polaris-react/scripts/profiler.js | jq '[group_by(.phase) | .[] | {phase: .[0].phase, actualDuration: [.[] | .actualDuration] | add}]'; echo ','; done; echo '[]]') | jq "add | [group_by(.phase) | .[] | {(.[0].phase): [.[] | .actualDuration] | add | (. / $COUNT)}] | add"
{
  "mount": 2004.360000360012,
  "nested-update": 690.3900000452995,
  "update": 1618.9700002014638
}
```

I'd like to leave it in for now if possible?

**Review by kyledurand — APPROVED** [review]
I've never really found this data to be reliable or useful 👍 

I think we should figure out a better way to compare component size on a case by case basis, like when there could be a big change to a heavily used component (Box). 

I think it would be better to compare core admin pages in staging vs prod using observe if possible. That would also be a pretty manual process

**Comment by alex-page** [comment]
Oops I missed @jesstelford's comment above. Going to keep this for now as it is being used!

Revert PR https://github.com/Shopify/polaris/pull/11386

**Pull request merged**
