### PR TITLE
[polaris.shopify.com] Make public/images match the content directory

### PR DESCRIPTION
**Pull request by alex-page**
This needs to be broken into multiple PR's probably one for each checkbox below. Wow. 1000 files changed 🤙

## polaris-react

**clean up** 
- [x] https://github.com/Shopify/polaris/pull/6536
- [x] https://github.com/Shopify/polaris/pull/6551
- [ ] Updated `src/components/**/README.md` file images to match the current site image locations _(404 on GitHub but could be useful if we need to automate any migrations of content)_

## polaris.shopify.com

**image architecture matching content** 
- [ ] `public/images` follows `content` directory structure unless its a global image
- [ ] Migrated used images from `images-from-old-website`
- [x] https://github.com/Shopify/polaris/pull/6561
- [x] https://github.com/Shopify/polaris/pull/6560
- [x] https://github.com/Shopify/polaris/pull/6568
- [x] https://github.com/Shopify/polaris/pull/6567
- [x] Removed logic to transform image paths in `markdown.mjs`
- [ ] Migrated image paths for all `/foundations` pages
- [ ] Migrated image paths for all `/contributing` pages
- [ ] Migrated image paths for all `/components` pages

**Removed mobile components, mobile examples, documentation and references**
- [x] https://github.com/Shopify/polaris/pull/6548
- [x] https://github.com/Shopify/polaris/pull/6549
- [x] https://github.com/Shopify/polaris/pull/6551
- [x] https://github.com/Shopify/polaris/pull/6552
- [x] https://github.com/Shopify/polaris/pull/6554
- [x] https://github.com/Shopify/polaris/pull/6553

**Use public directory instead of imports**
- [ ] Moved `Homepage.tsx` images to `/images` and replaced imports with paths

**Misc**
- [x] Fixed broken image in `card-with-flushed-sections.tsx`
- [x] https://github.com/Shopify/polaris/pull/6569

### CODE REVIEW

**Comment by martenbjork** [comment]
Amazing! My only comment is this:

> Use public directory instead of imports

I think, `next/Image` requires width and height attributes when serving stuff from /public whereas a direct import can omit these attributes.

**Review by martenbjork — APPROVED** [review]
Preemptive approve

**Comment by alex-page** [comment]
> I think, next/Image requires width and height attributes when serving stuff from /public whereas a direct import can omit these attributes.

TIL. It looks like we have height and width everywhere so I think we shouldn't import these images.

**Comment by alex-page** [comment]
@martenbjork this PR is now moving images and changing directories in markdown. I don't think I should split this up any more. Let me know what you think.

**Review by martenbjork — APPROVED** [review]

**Comment by martenbjork** [comment]
🔥🔥🔥🔥🔥

**Pull request merged**
