### PR TITLE
[RangeSlider] Add magic tone

### PR DESCRIPTION
**Pull request by matallo**
### WHY are these changes introduced?

This PR introduces a new `tone` prop with a possible value "magic" for determining the values in the component have been generated by AI. It uses the `--p-color-bg-fill-magic` token.

Screenshot 2024-01-18 at 8 06 59 PM

references https://github.com/Shopify/polaris/issues/10152

### WHAT is this pull request doing?

This is a followup of https://github.com/Shopify/polaris/pull/10819 and follows the pattern suggested by the Polaris team.

### How to 🎩

In Storybook

http://localhost:6006/?path=/story/all-components-rangeslider--magic

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [x] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Comment by alex-page** [comment]
@matallo what is stopping you from adding RangeSlider to magic-ui and doing a CSS override? Does this need to be in Polaris ASAP? Are 3P app developers going to need these features?

**Review by mathildebuenerd — COMMENTED** [review]
Code looks good but I wasn't able to tophat. I checked out your branch on my own spin instance but storybook is failing to run. Can you provide a spin link for me to tophat?

**Comment by mathildebuenerd** [comment]
> @matallo what is stopping you from adding RangeSlider to magic-ui and doing a CSS override? Does this need to be in Polaris ASAP? Are 3P app developers going to need these features?

@alex-page, the same prop got added to several Polaris components already, including TextField, Checkbox, RadioButton, Select and ChoiceList. 

At the moment I don't think 3P app developers are going to need this feature. In general, do we consider it a bad practice to add a prop to Polaris for something that's required in the admin, but not for 3P app developers?

**Review by chloerice — APPROVED** [review]
✨ 🚀

**Comment by matallo** [comment]
> what is stopping you from adding RangeSlider to magic-ui and doing a CSS override?

That can be a solution, we're doing something similar for `RichTextEditor`. As @mathildebuenerd mentioned I'm following the same pattern as prior components with `tone="magic"` but there's a wider discussion to be had.

> Does this need to be in Polaris ASAP? Are 3P app developers going to need these features?

I don't think so immediately, but I'll let the team using this to answer. Currently the feature is behind a beta flag for the Admin if I'm not wrong.

**Pull request closed without merging**
