### PR TITLE
8220/support old patterns

### LINKED ISSUE #8220: Remove current pattern index from site IA
Based on the decision from #8024 

Design tasks
- [x] Write copy for the banner on the new pattern index
- [x] Write copy for the banner on the old pattern index
- [x] Find appropriate location for legacy/deprecated content (site-wide)

Eng tasks
- [x] Move the current index to new location index and remove it from general IA, nav, search, etc
- [x] Update the new pattern index banner copy and link to the new location for old index
- [x] Remove `Page layouts` and `Design patterns` pages
- [x] Move `Error messages` and `Help content` pages to the `Content` section
- [x] Add "legacy" label and informative banner to `Loading`, `New badge`, `Pickers`, and `Text Fields` pages
- [ ] Complete fast-follow tasks in [this comment](https://github.com/Shopify/polaris/issues/8220#issuecomment-1442238819)

### PR DESCRIPTION
**Pull request by gwyneplaine**
- MVP new patterns implementation
- remove and move old pattern pages
- add page-layout.md back
- update page-layouts content
- move legacy pattern content to patterns-legacy folder
- move old patterns.tsx file to patterns-legacy.tsx
- update catch all slug file to ignore patterns but include patterns-legacy content folder
- logic to hide legacy pages from nav
- UI for status, and noIndex flag for bots

### WHY are these changes introduced?

Fixes #0000 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Comment by gwyneplaine** [comment]
@johanstromqvist @SeanyB , @jesstelford  raised a really good point around the ask in the linked issue to: 
> Remove Page layouts and Design patterns pages
This will likely break any existing links to these pattern pages. 

At the moment I've added copy from the page layouts pattern page that links to the resource details, and app index layout pages respectively. Is there a requisite solution for the design patterns page? 

Deleting it whole sale without either a redirect to a new pattern page or copy listing deprecation feels like poor UX for our users. Apologies if this is a conversation that has already happened

**Comment by johanstromqvist** [comment]
> Is there a requisite solution for the design patterns page?

Good question! Let's keep it on the legacy index for now. The value is low but not still somewhat accurate. There's no risk in referencing it. The alternative imo is to remove it and redirect to the pattern index. I would assume the risk and damage is low for that too. Any thought on that @SeanyB?

**Comment by SeanyB** [comment]
> Remove Page layouts and Design patterns pages
> This will likely break any existing links to these pattern pages.

Spicy take: let's remove them both. The Page layouts pattern includes tons of guidance that isn't relevant as we move away from the older Layout component and towards the layout primitives. The Design patterns page is of dubious value because it's just a list of three principles.

I highly doubt that there are folks keeping bookmarks of these two particular pages, so I'm not concerned if the URLs result in 404s. However, if it is trivial to redirect them both to the new Patterns overview page, I'm happy with that too.

**Comment by jesstelford** [comment]
> let's remove them both

Agreed 100% - their content is out dated and we don't want folks stumbling on it and getting confused!

> I'm not concerned if the URLs result in 404s

**Proposal**: Have the pages 404 _(good to indicate "This thing is gone" rather than redirecting to the index page where they might still hunt for the "Page layouts" pattern and get frustrated)_, and also include a note that it's been removed + link to either the new page-based layouts, or to the pattern index page.

That way, we catch anyone who has bookmarked it, or if there's a latent link from shopify.dev, a blog post, or google, etc, and redirect them to where they _probably_ want to go to find the latest info. Nothing more frustrating than 404s IMO.

**Review by jesstelford — APPROVED** [review]

**Comment by gwyneplaine** [comment]
@SeanyB  @jesstelford  @johanstromqvist  going to merge this first so as not to block additional work coming in the pipeline. 
Please feel free to continue the conversation in #8220 and will action the decided upon outcome in a separate PR.

**Pull request merged**
