### PR TITLE
[IndexTable] Ensure sticky calculation occurs when children prop changes

### PR DESCRIPTION
**Pull request by mrcthms**
### WHY are these changes introduced?

Fixes https://shopify.slack.com/archives/C4Y8N30KD/p1706554593503719

Fixes an issue where when using nested expandable child rows, the sticky select all actions bar would not react to changes in the dimensions of the table.

### How to 🎩

Tophatting Snapshot in Spin: https://admin.web.notes-explore.marc-thomas.eu.spin.dev/store/shop1/products/4

### 🎩 checklist

- [x] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by tatianau — APPROVED** [review]
🎉

**Review by LA1CH3 — APPROVED** [review]
TYSM for the quick fix on this!

**Pull request merged**
