### PR TITLE
Remove hardcoded breakpoints tokens from components

### PR DESCRIPTION
**Pull request by aaronccasanova**
### WHAT is this pull request doing?

Remove (recently added) hardcoded `breakpoints` tokens from the `IndexTable` and `ResourceList` components.

Before:

https://user-images.githubusercontent.com/32409546/177870087-a139c090-b7b1-4fae-a36e-e1cae753ddea.mov

After:

https://user-images.githubusercontent.com/32409546/177870100-32ef5369-a3bf-4de9-914a-4bd8ed161285.mov

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by alex-page — APPROVED** [review]
Love this clean up. Thank you @aaronccasanova

**Review by gui-santos — APPROVED** [review]

**Review by kyledurand — APPROVED** [review]
Code looks good to me. Great clean up 👍

**Comment by aaronccasanova** [comment]
Update: I will follow up on this PR after Polaris v10 is released.

**Review by alex-page — APPROVED** [review]

**Comment by alex-page** [comment]
@aaronccasanova this still looks like a useful change. Let me know.

**Comment by aaronccasanova** [comment]
Absolutely @alex-page! Although, I do think we should rebase and merge post v11 to avoid introducing more changes to the mix.

**Comment by alex-page** [comment]
Ahhh this is a good PR lost with time 💔

**Pull request closed without merging**
