### PR TITLE
[next] Add multi-theme support to Polaris

### PR DESCRIPTION
**Pull request by aaronccasanova**
Continuation of https://github.com/Shopify/polaris/pull/10290

This PR contains breaking changes in both Polaris and Polaris tokens to enable global multi-theme support.

### Polaris changes:
- Updated the `AppProvider` component
  - **Breaking:** Removed `features` class name toggle from `setRootAttributes`
  - Added a new `theme` prop which accepts a Polaris tokens `ThemeName`. This prop is used for:
    - Toggling the theme class names on the root element, and
    - Setting the theme object on the root `ThemeContext.Provider`
- Added global theme toggle to Storybook

### Polaris tokens changes:
- **Breaking:** Moved the `light-uplift` overrides to base token groups (e.g. `light-uplift` is now the default theme)
- Normalized specificity of the default theme

> [!NOTE]
> Currently, our browser support requirements don't allow us to use the `:where()` selector to flatten our theme class name specificity to `0`. Therefore, I'm proposing a solution that normalizes the specificity to `11`.

**Theme selector breakdown:**
- `:root, html.p-<default-variant-theme>{...}` - The generated stylesheet outputs the default theme custom properties to both the `:root` selector and a dedicated `html.p-*` selector. This allows the page to apply the default theme via `:root` initially (specificity `10`) and then `html.p-*` when the `AppProvider` initializes (specificity `11`)
 - `html.p-<variant-theme-1>{...}html.p-<variant-theme-2> {...}html.p-...` - All other variant themes have specificity `11`
 - Thus, theme classes in the Admin should always have specificity `11` after rendering the `AppProvider`

**Example** theme selector output:

Screenshot 2023-09-12 at 3 12 07 PM

- Initialized a new `light-high-contrast-experimental` theme

https://github.com/Shopify/polaris/assets/32409546/ad228532-e277-4107-af5c-95511f3e3297

### CODE REVIEW

**Comment by laurkim** [comment]
Looking at the 300+ pending baselines that need to be accepted, I think a majority of them are coming from the fact that the font size is using the `--p-font-size-100` token since we're no longer using the se23 flag class. I think this [line](https://github.com/Shopify/polaris/blob/dc93e5b5d7f426476fac2b66c87ac645c25b0159/polaris-react/src/components/AppProvider/AppProvider.scss#L10) in `AppProvider.scss` just needs to be updated to use the `--p-font-size-80-experimental` token that we used to apply behind the flag [here](https://github.com/Shopify/polaris/blob/dc93e5b5d7f426476fac2b66c87ac645c25b0159/polaris-react/src/components/AppProvider/AppProvider.scss#L20-L22).

Edit— 
I pushed up a [commit](https://github.com/Shopify/polaris/pull/10423/commits/fe837981ffede6688dadce9b2d3f16978d8045a4) to fix the font styles in AppProvider and cleaned up some duplicate styling. Also pushed up a [commit](https://github.com/Shopify/polaris/pull/10423/commits/5f51c9d2bb4a71ec74881e14f4df2dad30d9d4c0) to consolidate some straggling se23 styles in IndexTable that was missed and causing some chromatic diff.

**Review by laurkim — APPROVED** [review]
Nice! 🌟 🚀

**Review by sam-b-rose — APPROVED** [review]
Very nice work! What a contrast of a difference ☯️ 💯

**Review by chloerice — APPROVED** [review]
🚢 🚢 🚢

**Pull request merged**
