### PR TITLE
[Icons] Add "enter" icon

### PR DESCRIPTION
**Pull request by zecarlostorre**
### WHY are these changes introduced?

In the context of new customer accounts, we have the need to explain how/when buyers will log in to their account. So @heydouble-a proposed a more general icon for the  action of buyers and/or merchants "authenticating" "gaining access to" or "log in."

### WHAT is this pull request doing?

New icon:
Screenshot 2023-01-20 at 21 40 18

### CODE REVIEW

**Review by sarahill — APPROVED** [review]
Looks good! I think the error might be something with the svg but I can't quite tell what it is. Maybe a dev can take a look.

**Comment by alex-page** [comment]
@zecarlostorre it looks like the SVG has some values that are not supported in mobile devices. You might need to simplify the svg. If you are struggling to do this reach out to any developer on our team.
```
only has <polygon>s that only use the [fill, points] attributes
```

**Comment by zecarlostorre** [comment]
Thanks for the 👀 @alex-page & @sarahill , I think I fixed the problem now.
Let me know if I can merge my very first PR. 😛

**Comment by zecarlostorre** [comment]
Thanks for the eyes @sarahill & @alex-page! I think I fixed it.
Let me know if it's good to merge (this is my first PR 😁 btw)

**Review by kyledurand — APPROVED** [review]
Just removed the duplicate changeset entry, changed from patch to minor since this is an enhancement. I think this is good to go now. Thanks José!

**Comment by zecarlostorre** [comment]
Thanks @kyledurand! 🙌

**Pull request merged**
