### PR TITLE
[topbar]: fixes the color of the hamburger icon

### PR DESCRIPTION
**Pull request by lbenie**
### WHY are these changes introduced?

Fixes: https://github.com/Shopify/polaris-internal/issues/1311 

### WHAT is this pull request doing?
Relies on the color CSS attribute so that the polaris Icon can inherit and apply the color properly

```css
.Polaris-Icon svg {
  fill: currentColor;
}
```

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [x] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by bradfeehan — APPROVED** [review]
Approving as IMOC

**Comment by gwyneplaine** [comment]
lgtm 👍

**Review by gwyneplaine — APPROVED** [review]

**Pull request merged**
