### PR TITLE
fix(polaris.shopify.com): `TokenList.Item` url for clickable search result

### LINKED ISSUE #11056: [polaris.shopify.com] 404 not found at /tokens/zIndex
When searching "z-index" in the global search box and clicking any "View token" button, it's showing a "There’s no page at this address" error.

URL leading to 404:

```
https://polaris.shopify.com/tokens/zIndex#tokens-z-index-1
```

<details>
<summary>Screenshot of link leading to 404</summary>
Screenshot 2023-10-30 at 14 24 25

</details>

<details>
<summary>Screenshot of error page</summary>
Screenshot 2023-10-30 at 14 26 04

</details>

### PR DESCRIPTION
**Pull request by SMAKSS**
### WHY are these changes introduced?

Fixes #11056 

### WHAT is this pull request doing?

When I investigated the problem, I noticed the `api/search/v0` will return a perfect URL for each result it gives, so instead of manually creating the link, I used the returned URL by the API, which navigates to the correct page.

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Comment by sam-b-rose** [comment]
Hi @SMAKSS ! Thanks for the PR 🙏 

Referring to the original issue #11056, I think the 404 is due to the casing of `zIndex` in the URL. If we just make the formatting of the URL link kebab case, that should fix the broken link.

I am hesitant to point users to the API url since I think we just want to direct them to the main token page for the specific token group.

**Comment by SMAKSS** [comment]
Hi @sam-b-rose, there were two glitches in the URL. The first one was the problem with the `zIndex` case, and the second one was about every link to tokens starting with `tokens-**`. It won't break anything and result in 404 pages, but it will result in not scrolling to the proper token in the list, and it will always stay on top of the token page because the actual links do not start with the `tokens-**` convention. But as you said, if we only want to redirect without scrolling to the proper view (Which I believe the actual functionality of it was intended to do this action, _speaking as a general user_), that's a valid point, and I can change the PR to reflect the result of fixing the `zIndex` casing.

Would you happen to have any suggestions for it?

**Comment by SMAKSS** [comment]
@sam-b-rose 
Hi again; I wanted to say the link is still broken. Do you think you have any plans to fix this?

**Comment by sam-b-rose** [comment]
Thank you for following up @SMAKSS! This totally slipped my focus. I appreciate you looking into this issue. I did find a simple fix here (#11218) which should fix the 404 and scroll-to-token issues.

Thank you for your help digging into this bug 🙏

**Comment by SMAKSS** [comment]
Thank you for responding and fixing the bug, @sam-b-rose. I will close this PR as it's not needed anymore.

**Pull request closed without merging**
