### PR TITLE
[FormLayout] Fix child spacing and add support for grouping inputs vertically

### PR DESCRIPTION
**Pull request by chloerice**
### WHY are these changes introduced?

The refactor of `FormLayout` to use layout components instead of the old margin flex hack that shipped in https://github.com/Shopify/polaris/pull/11012 caused a hierarchy regression because using `BlockStack` `gap` gives ungrouped inputs and `FormLayout.Group` the same surrounding spacing.

### WHAT is this pull request doing?

This PR: 

- Reverts `FormLayout` and `FormLayout.Group` back to a `div` with the correct spacing configured around child `Item` and `Group` components
- Cleans up and beefs up the `FormLayout` stories
- Adds a `variant` prop to `FormLayout.Group` to support composition of both vertical and horizontal input groups (currently only inline groups are supported)
- Adds support for nested `FormLayout.Group`s (`Group` children are now prevented from being wrapped with `Item`)

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [ ] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Comment by lgriffee** [comment]
@chloerice Just wanted to check if this PR is still active?

**Comment by lgriffee** [comment]
@chloerice Wanted to let you know I [created an accompanying issue for this PR](https://github.com/Shopify/temp-project-mover-Archetypically-20250501100408/issues/134) since I got a request to remove any PRs from our project board. Feel free to edit the issue if needed!

**Comment by shawn-shellenbarger** [comment]
@chloerice I was in the process of opening an issue in regards to `children` of `FormLayout.Group` having a `gap` value of `300`, rather than `400`. Could you confirm if this PR aims to address that? Or should I open another issue to track that?

**Comment by chloerice** [comment]
> @chloerice I was in the process of opening an issue in regards to `children` of `FormLayout.Group` having a `gap` value of `300`, rather than `400`. Could you confirm if this PR aims to address that? Or should I open another issue to track that?

Hey @shawn-shellenbarger 👋🏽 I believe there's already two issues tracking that: Shopify/temp-project-mover-Archetypically-20250501100408#156 and Shopify/temp-project-mover-Archetypically-20250501100408#134, which this does address 💯

**Comment by chloerice** [comment]
Just a quick update: I've been swamped with priority issues and haven't had time to do a final tophat. Will get back to this in the next week or two!

**Pull request closed without merging**
