### PR TITLE
[Icons] Add icons for image editing

### PR DESCRIPTION
**Pull request by dGoligorsky**
### WHY are these changes introduced?

Some icons in use on image editing features are hardcoded svgs. 
This change introduces Polaris icons for `Crop`, `FlipHorizontal`, `FlipVertical`, `ImageMagic`, `RotateteLeft`, `RotateRight`.
This not only allows the icons to exist in Polaris for web, but also allows them to get the Mobile icon size scaling.

### WHAT is this pull request doing?

image

### CODE REVIEW

**Review by heyjoethomas — CHANGES_REQUESTED** [review]
Is there a reason all the icon names start with a `!`?

**Comment by dGoligorsky** [comment]
> Is there a reason all the icon names start with a `!`?

Because I forgot to remove it 😅
I put them there to get the changed files at the top of the file list. 
Will fix now, TY.

**Review by heyjoethomas — CHANGES_REQUESTED** [review]
Looks like `RemoveBackground` got the wrong svg
Screenshot 2024-04-03 at 10 15 15 AM

**Comment by alex-page** [comment]
@dGoligorsky is there any urgency to ship this? Trying to balance a couple of icon changes. Happy to get this through but just wanted to check first.

**Comment by dGoligorsky** [comment]
@heyjoethomas ack... fixed 👍 Thanks for that.

@alex-page I'll ping you with deets since this is a public repo.

**Review by alex-page — APPROVED** [review]

**Review by sam-b-rose — CHANGES_REQUESTED** [review]
Looks good! Just a few changes needed:

- For the `name` property, use sentence case (`RemoveBackground` -> `Remove background`)
- Remove `clip-path` attribute from SVGs
- Add the `Icon` suffix to the `.svg` filenames (`FlipVertical.svg` -> `FlipVerticalIcon.svg`)

Happy to hep with any of these changes!

**Review by heyjoethomas — APPROVED** [review]

**Review by sam-b-rose — APPROVED** [review]
Looks good! Thanks @dGoligorsky

**Pull request merged**
