### PR TITLE
[Layout foundations] Update `SkeletonPage` title to have fixed height

### PR DESCRIPTION
**Pull request by chazdean**
### WHY are these changes introduced?

Adds consistency to `SkeletonPage` by giving the skeleton title a fixed height regardless if the `primaryAction` prop is being used or not

### WHAT is this pull request doing?

- Centers the title skeleton by adding `blockStart` and `blockEnd` padding
- Increases title height back to `28px` so that with `8px` of extra padding, title container can match the height of the `primaryAction` skeleton at `36px`

#### With primaryAction skeleton
Screenshot 2023-01-18 at 8 37 53 AM

#### Without primaryAction skeleton
Screenshot 2023-01-18 at 8 38 50 AM

### How to 🎩

[Spin Link](https://admin.web.web-6n2m.chaz-dean.us.spin.dev/store/shop1/) (Updated)

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Comment by kyledurand** [comment]
This horizontal alignment looks off. Is that intentional?

Before | After
---|---
image | image

**Comment by chazdean** [comment]
> This horizontal alignment looks off. Is that intentional?
> 
> Before	After
> image	image

@kyledurand Yeah the alignment definitely looks off. There looks to be `padding-left` on the `.HeaderTitleWrapper` selector in `ResourceList.scss` that is no longer needed. I created a separate [issue](https://github.com/Shopify/polaris/issues/8078) for this 👍🏾

**Comment by sarahill** [comment]
Seeing some horizontal misalignment on the [Customers index page](https://admin.web.web-yng6.chaz-dean.us.spin.dev/store/shop1/customers)

- I'm assuming this is because there's a picker in the page header. I'm guessing the same issue will occur on the order index when there are multiple locations to choose from.
- It's also loosing left/right padding at smaller breakpoints

image

image

**Comment by chazdean** [comment]
> Seeing some horizontal misalignment on the [Customers index page](https://admin.web.web-yng6.chaz-dean.us.spin.dev/store/shop1/customers)
> 
> * I'm assuming this is because there's a picker in the page header. I'm guessing the same issue will occur on the order index when there are multiple locations to choose from.
> * It's also loosing left/right padding at smaller breakpoints
> 

@sarahill This issue is present in production as well. Here a [custom css skeleton title header](https://github.com/Shopify/web/blob/main/app/sections/Customers/CustomerListNext/components/CustomerListNextSkeleton/CustomerListNextSkeleton.tsx) is being used causing these differences which will have to be revisited 😕. The orders index page should be good though as it will use our new rebuilt `SkeletonPage` header regardless if there are multiple locations to choose from 👍🏾

**Comment by kyledurand** [comment]
Just merged @aveline's PR, can you rebase against batch 2 and update spin @chazdean?

**Comment by chazdean** [comment]
@kyledurand good to go 👍🏾

**Review by yurm04 — APPROVED** [review]
there are some chromatic diffs that look a bit wonky that might just be the same issue we've been dealing with throughout the batches. Code LGTM, maybe needs one more pass in chromatic for UX review 👍

**Review by aveline — APPROVED** [review]
Chromatic changes need to be reviewed, the change in title heights make sense and need to be accepted, but not sure what's going on with the centering. Otherwise looks good 👍

**Review by sarahill — APPROVED** [review]
A couple of the chromatic diffs look off but look and function as expected in Storybook ✅

**Pull request merged**
