### PR TITLE
[ContextualSaveBar] Scroll to content if scroll top is less than top bar height

### PR DESCRIPTION
**Pull request by kyledurand**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-summer-editions/issues/959

When a merchant is scrolled to the top of the page and makes a change, the contextual save bar covers primary and secondary page actions, giving the illusion that these are no longer accessible. 

### WHAT is this pull request doing?

This PR scrolls to the content when the merchant is near the top of the page (hasn't scrolled beyond the top bar height)

If the merchant has scrolled beyond that threshold, no content jump will occur when the save bar is active

### How to 🎩

[Spin](https://admin.web.web-dm8y.kyle-durand.us.spin.dev/store/shop1/shipping_labels)

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by laurkim — APPROVED** [review]
💯 🙌

**Comment by kyledurand** [comment]
Closing in favor of an alternate solution posted in the issue

**Pull request closed without merging**
