### PR TITLE
[New] magic chat icons

### PR DESCRIPTION
**Pull request by jonrundle**
### WHY are these changes introduced?

Adds new icons necessary for the Magic Chat header actions

### WHAT is this pull request doing?

Added 3 new icons:
- Dock Side Major
- Dock Floating Major
- Minus Major
Screenshot 2023-04-28 at 11 52 22 AM

### CODE REVIEW

**Review by dGoligorsky — APPROVED** [review]
🤗

**Comment by kyledurand** [comment]
Please ping @Shopify/polaris-eng if there are [failures with your build](https://github.com/Shopify/polaris/actions/runs/4832521107/jobs/8611400433) before you ship and we'll help you out @jonrundle

**Comment by jonrundle** [comment]
@Shopify/polaris-eng could use some help on this, didn't realize there was an error here before merging 🙏

**Comment by jonrundle** [comment]
@kyledurand awesome, thanks! sorry about that, didn't realize there was some there before I merged 🙈

**Pull request merged**
