### PR TITLE
Add migration to `replace-static-mixins-with-declarations`

### LINKED ISSUE #7148: Migrate static mixins
Write a new `@shopify/polaris-migrator` script to replace the following static mixins with declarations:
- `@mixin text-emphasis-subdued`
- `@mixin text-emphasis-strong`
- `@mixin text-emphasis-normal`

### PR DESCRIPTION
**Pull request by aaronccasanova**
Closes #7148 

Add `replace-static-mixins-with-declarations` migration script.

Running `npx @shopify/polaris-migrator replace-static-mixins-with-declarations "**/*.scss"` will replace the following mixins with declarations:
- `@include text-emphasis-subdued;`
- `@include text-emphasis-strong;`
- `@include text-emphasis-normal;`

### CODE REVIEW

**Review by sam-b-rose — APPROVED** [review]

**Comment by sam-b-rose** [comment]
Looks great! Just needs a changeset 🦋 🚀

**Review by lgriffee — APPROVED** [review]
LGTM! 💯🚢✨🎉

**Pull request merged**
