### PR TITLE
[polaris.shopify.com] Use `@vercel/og` to create og images

### PR DESCRIPTION
**Pull request by kyledurand**
image

This change essentially removes the component snapshots from og images. Is that an acceptable trade off?

Component images before / after
Before | After
---|---
image | image

TODO:
- [ ] Fix typography
- [ ] Fix squashed bag icon

### CODE REVIEW

**Comment by alex-page** [comment]
> This change essentially removes the component snapshots from og images. Is that an acceptable trade off?

@kyledurand any context on why we lose this functionality?

I also notice the typography seems to be different in the og-image.

**Comment by kyledurand** [comment]
In my mind we'd have to keep puppeteer, simplify the gen og script so it only grabs the screenshots of components, and link to them from the og-image generator. Do you know of a better way to get component screenshots?

I have to fix typography and also the bag icon is squished for some reason

**Comment by martenbjork** [comment]
I think having custom assets for each page is a big win. It makes it the cards more engaging and easier to discern in a list of links.

The puppeteer script isn't actually rendering the React components, it's just grabbing the corresponding image in the `/public` folder. Could we import them all and then render the right one conditionally, like? Like `componentImages[slug]` or something like that.

Also: the foundations pages fetches unique icons for each page and adds it to the card. Could we import all of those as well and render the correct one? `icons[slug]`

**Comment by kyledurand** [comment]
> I think having custom assets for each page is a big win

Yes absolutely. When I put this PR up I thought these images were being generated on the fly, now I know they live in the public folder and are accessible in the OG image generation step. I'll revisit this PR soon

**Comment by alex-page** [comment]
@kyledurand this will be unblocked when v11 ships and nodejs versions are bumped.

**Pull request closed without merging**
