### PR TITLE
[IndexTable] Use correct index in the sticky header

### PR DESCRIPTION
**Pull request by jhalvorson**
### WHY are these changes introduced?

In #11342 I changed the index that's used when calculating the width of the header cell. This didn't take into account selectable rows. This PR checks if the `selectable` prop is set, if so then add `1` to the index, otherwise, use the index directly.

I've added a new [storybook story](http://localhost:6006/?path=/story/all-components-indextable--with-long-data-set-selectable) to test this.

### How to 🎩

In Storybook test the following components:
- http://localhost:6006/?path=/story/all-components-indextable--with-long-data-set-selectable
- http://localhost:6006/?path=/story/all-components-indextable--with-long-data-set-non-selectable

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [x] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by jiricrispeyn — APPROVED** [review]
Mainly tested scrolling behavior on selectable list. Feel free to reach out for any a11y or different browser / device testing.


https://github.com/Shopify/polaris/assets/3664238/db3ffd50-fb79-47af-996f-871ded1be8ee

**Review by sophschneider — APPROVED** [review]
Thanks for fixing this! Tophatted on storybook, i will tophat in the admin once this is part of the upcoming release 🙌

**Comment by sophschneider** [comment]
I'm going to merge this to main to unblock the next polaris release

**Pull request merged**
