### PR TITLE
[IndexTable] Standardize hover styles to make consisitent with ResourceList

### LINKED ISSUE #4319: [Bug] ResourceList and IndexTable hover states should be the same
## Issue summary

The `ResourceList` and `IndexTable` components have two different hover states.

## Expected behavior

The interaction states should be the same.

## Actual behavior

`ResourceList` items are gray when hovered, while `IndexTable` items are blue when hovered.

| ResourceList | IndexTable |
|---|---|
|Screen Shot 2021-07-15 at 6 18 12 PM|Screen Shot 2021-07-15 at 6 17 57 PM|

## Steps to reproduce the problem

1. View the `ResourceList` docs and hover over items in the examples
2. View the `IndexTable` docs and hover over items in the examples

### PR DESCRIPTION
**Pull request by juwanpetty**
### Why are these changes introduced?
Fixes #4319  

`ResourceList` items are gray when hovered, while `IndexTable` items are blue when hovered, creating style inconsistency between the two components.

| ResourceList | IndexTable |
|---|---|
|Screen Shot 2021-07-15 at 6 18 12 PM|Screen Shot 2021-07-15 at 6 17 57 PM|

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';

import {Page, IndexTable, TextStyle, Card, useIndexResourceState} from '../src';

export function Playground() {
  const customers = [
    {
      id: '3411',
      url: 'customers/341',
      name: 'Mae Jemison',
      location: 'Decatur, USA',
      orders: 20,
      amountSpent: '$2,400',
    },
    {
      id: '2561',
      url: 'customers/256',
      name: 'Ellen Ochoa',
      location: 'Los Angeles, USA',
      orders: 30,
      amountSpent: '$140',
    },
  ];
  const resourceName = {
    singular: 'customer',
    plural: 'customers',
  };

  const {
    selectedResources,
    allResourcesSelected,
    handleSelectionChange,
  } = useIndexResourceState(customers);

  const rowMarkup = customers.map(
    ({id, name, location, orders, amountSpent}, index) => (
      <IndexTable.Row
        id={id}
        key={id}
        selected={selectedResources.includes(id)}
        position={index}
      >
        <IndexTable.Cell>
          <TextStyle variation="strong">{name}</TextStyle>
        </IndexTable.Cell>
        <IndexTable.Cell>{location}</IndexTable.Cell>
        <IndexTable.Cell>{orders}</IndexTable.Cell>
        <IndexTable.Cell>{amountSpent}</IndexTable.Cell>
      </IndexTable.Row>
    ),
  );
  return (
    <Page title="Playground">
      <Card>
        <IndexTable
          resourceName={resourceName}
          itemCount={customers.length}
          selectedItemsCount={
            allResourcesSelected ? 'All' : selectedResources.length
          }
          onSelectionChange={handleSelectionChange}
          headings={[
            {title: 'Name'},
            {title: 'Location'},
            {title: 'Order count'},
            {title: 'Amount spent'},
          ]}
        >
          {rowMarkup}
        </IndexTable>
      </Card>
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
- [ ] For visual design changes, ping @ sarahill to update the Polaris UI kit

### CODE REVIEW

**Review by alex-page — APPROVED** [review]
@sarahill does this change look okay to you?

**Comment by sarahill** [comment]
Is this still an issue? When I look at the style guide they look the same 🤔 

image

image

**Comment by alex-page** [comment]
@sarahill I am seeing the same thing. Odd! This definitely was an issue. @juwanpetty is there a specific implementation this issue occurs on?

**Comment by juwanpetty** [comment]
Checking and can't find it anymore, this might have been fixed before this PR was out

**Comment by juwanpetty** [comment]
Checked the git file history and can confirm there was a PR that fixed this already, going to close this PR

**Pull request closed without merging**
