### PR TITLE
Create migration guidance for `icon-size()` function

### LINKED ISSUE #5045: Create migration guidance for `icon-size()` mixin

### PR DESCRIPTION
**Pull request by romellogoodman**
### WHY are these changes introduced?

Fixes #5045

### WHAT is this pull request doing?

- Adding documentation for the`icon-size()` function to our migration guide

<hr>

### Helpful References

- #4923
- #4990

### CODE REVIEW

**Comment by ghost** [comment]
👋 Thanks for opening your first pull request. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by romellogoodman** [comment]
So the changelog step is failing but this change is already documented on this line: https://github.com/Shopify/polaris-react/blob/v9.0.0-major/UNRELEASED-v9.md?plain=1#L48. Should I add a link to this PR to the line as well?

**Comment by aveline** [comment]
Adding the `Skip Changelog` label will fix the changelog step 😁

**Review by aveline — APPROVED** [review]
🎉

**Review by lgriffee — APPROVED** [review]
LGTM!! 🎉🚢✨💯

**Review by aaronccasanova — APPROVED** [review]
Looks good! Not sure if there is a separate GitHub issue for this, but my `icon-size()` PR also `Replaced existing '--p-icon-size' tokens with '--p-icon-size-small'`. I think we should include that somewhere in this doc 👍

**Comment by lgriffee** [comment]
> Not sure if there is a separate GitHub issue for this, but my icon-size() PR also Replaced existing '--p-icon-size' tokens with '--p-icon-size-small'. I think we should include that somewhere in this doc 👍

@aaronccasanova Aveline included it with her CSS Custom Properties section PR! (it's on line 84)

**Review by alex-page — APPROVED** [review]

**Comment by romellogoodman** [comment]
For transparency, force merged this PR. The Chromatic step was hanging and we technically aren't observing that step for this PR.

**Comment by lgriffee** [comment]
💯 That's been happening to me too! I've been noticing Chromatic hanging on some PRs and not others recently 😣 Not sure what's going on there 😢

**Pull request merged**
