### PR TITLE
[IndexTable] Add hasZebraStriping optional prop

### LINKED ISSUE #8592: Add zebra striping to IndexTable
## Feature request summary

Add zebra striping option to IndexTable component.

## Rationale

Zebra striping is already available on the DataTable, so this will give designers the option to have the striping on IndexTable as well.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s :+1: upvotes to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

### PR DESCRIPTION
**Pull request by KateWood**
### WHY are these changes introduced?

Closes https://github.com/Shopify/polaris/issues/8592

The Pixels Index Redesign for Customer Events uses IndexTable and zebra striping is desired.

I used the same color variable as the zebra striping in [DataTable](https://github.com/Shopify/polaris/pull/5365/files#diff-afd7e6258c31974d33a41a0be5cae45bd14466b2e68b17725e11d884ba2647ec).

### WHAT is this pull request doing?

Adds `hasZebraStriping` optional prop on IndexTable.

screenshot of ZebraStriping in storybook

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Comment by blboyle** [comment]
Hey @KateWood! One of the things that we ran into when adding zebra striping to the DataTable was whether we would always start with the grey and whether that would start on the header or the first row. 

I mentioned this just to make sure that it's something you've thought about.

---

update: https://github.com/Shopify/polaris/pull/5365#issue-1184854479

You can see what I mean when looking at the "after" screenshot for the zebra striping section. The goal in our case was to allow the footer and header to stay consistent.

**Comment by KateWood** [comment]
> Hey @KateWood! One of the things that we ran into when adding zebra striping to the DataTable was whether we would always start with the grey and whether that would start on the header or the first row.
> 
> I mentioned this just to make sure that it's something you've thought about.
> 
> update: [#5365 (comment)](https://github.com/Shopify/polaris/pull/5365#issue-1184854479)
> 
> You can see what I mean when looking at the "after" screenshot for the zebra striping section. The goal in our case was to allow the footer and header to stay consistent.

Hi @blboyle ! IndexTable doesn't have a footer, so I think that doesn't apply here.

**Comment by blboyle** [comment]
@KateWood okay cool 👍🏻 

It's looking good! Excited to see this shipped!

When testing, I notice a few things: 

For these 3, I would say it's up to you as to whether that's how you want to go.
1. When the `condensed` prop is added, there is no zebra striping
2. Hovering over the row does not give the gray feedback for the rows that have the striping

3. When interacting with `lastColumnSticky` the borders only appear on the gray rows.

<details><summary><em>(open for screenshot)</em></summary>

[alt](https://screenshot.click/08-35-u6zpt-y5p56.png)
</details> 


4. The gray is also over-writing the status colouring which I think should be addressed

<details><summary><em>(open for screenshot)</em></summary>


[alt](https://screenshot.click/08-33-qucbk-ncqfq.png)
</details>

**Comment by KateWood** [comment]
@blboyle fixed! here's a video of those cases: https://screenshot.click/14-42-wqzd0-ruymv.mp4

**Review by blboyle — APPROVED** [review]
Looks great! Thanks for making those updates.

**Pull request merged**
