### PR TITLE
[Filters] Add `disableQueryField` Property

### PR DESCRIPTION
**Pull request by Stivaros**
### WHY are these changes introduced?

The `disable` property allows a developer to disable the entire component and the `hideQueryField` property enables a developer to hide the query field. Prior to this PR, there was no first-class way to disable the query field.

Hiding and showing a field can be a bit of a UX nightmare but sometimes we don't want users to be performing text searches.

### WHAT is this pull request doing?

It adds a `disableQueryField` property to the `Filters` component which will disable the `TextField` (aka "query field") when set to `true`. Please see below video for a demo in the browser.

<details>
  <summary>`disableQueryField` Demo Video</summary>
  https://user-images.githubusercontent.com/7734772/169001146-d3cc1e17-5672-4232-9c3c-9470a88340bc.mp4
</details>

### How to 🎩

Add `disableQueryFilter={true}` (or `false`) to any `<Filters>` component

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Comment by ghost** [comment]
👋 Thanks for opening your first pull request. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Review by kyledurand — APPROVED** [review]
Looks great @Stivaros 👏

**Comment by Stivaros** [comment]
Rebasing due to a merge conflict in `UNRELEASED.md`

**Comment by kyledurand** [comment]
We shipped a change yesterday which deleted UNRELEASED.md and now requires you to run `yarn changeset`. You'll have to rebase, run that command, add a quick note, and this should be good to go

**Comment by Stivaros** [comment]
> We shipped a change yesterday which deleted UNRELEASED.md and now requires you to run `yarn changeset`. You'll have to rebase, run that command, add a quick note, and this should be good to go

Ah, thanks. Are you happy with the changes introduced in [27eac2d](https://github.com/Shopify/polaris/pull/5832/commits/27eac2d1cf38f1c719b7123a53ba6d2a629994f5)?

**Comment by kyledurand** [comment]
That's perfect. Alex is taking the day off today so feel free to ship when 🟢 

I'm planning to cut a 9.9.0 release early next week as well

**Comment by Stivaros** [comment]
@kyledurand there's a pending change in the UI Tests check which requires manual intervention. Is that my remit or yours? It's as I expect - the query field is disabled in the screenshot.

**Comment by kyledurand** [comment]
> there's a pending change in the UI Tests check

I believe I approved that when I reviewed but you have to manually approve them on every new push. I marked it approved 👍

**Pull request merged**
