### PR TITLE
[TextField] Add required prop to TextField

### LINKED ISSUE #3512: TextField - Pass along required prop to input
## Feature request summary

The html input required prop enforces that an input has a value upon submit.  This would be helpful to be able to do with Polaris' `TextField` as well.

## Rationale

This would be easy to implement and provide a lot of extra functionality.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

### PR DESCRIPTION
**Pull request by dkershner6**
### WHY are these changes introduced?

Fixes #3512 

Easy, powerful change.

### WHAT is this pull request doing?

HTML Input elements have a required prop to ensure a value is provide, this allows it to be used with Polaris' TextField.

### CODE REVIEW

**Review by Tom-Bonnike — DISMISSED** [review]

**Comment by Tom-Bonnike** [comment]
For reference… the Polaris team [apparently doesn’t want this change](https://github.com/Shopify/polaris-react/issues/222#issuecomment-351565773) so this PR probably won’t get merged. 😕

**Comment by dkershner6** [comment]
> For reference… the Polaris team [apparently doesn’t want this change](https://github.com/Shopify/polaris-react/issues/222#issuecomment-351565773) so this PR probably won’t get merged. 😕

That's...odd.  This is definitely accessibility friendly...

Oh well, ill leave it here until someone definitively says something.

**Comment by chloerice** [comment]
Hey @dkershner6 thank you for contributing to the discussion around [this issue](https://github.com/Shopify/polaris-react/issues/222#issuecomment-351565773). I'm going to close this PR in lieu of https://github.com/Shopify/polaris/pull/4119

**Comment by bakura10** [comment]
@chloerice , can this issue be reconsidered? It might have been a good decision two years ago, but in 2024 Shopify is pushing hard Remix for app development. Remix's main selling point is to embrace the web built-in features and, especially, forms. Being able to add the `required` attribute to input easily would allow to easily use built-in client-side validation and improve merchant user experience.

**Comment by chloerice** [comment]
Hey @bakura10 👋🏽 There are API updates planned and `required` will be supported on all inputs when it ships, but it will be a while before it does. Stay tuned 🙏🏽

**Pull request closed without merging**
