### PR TITLE
Replace shadow bevel with simpler box shadow solution

### PR DESCRIPTION
**Pull request by sam-b-rose**
Closes https://github.com/Shopify/polaris-internal/issues/1095

This PR replaces the current shadow bevel solution with one that do not require pseudo elements and is less bug-prone.

Components affected:

- [Card](https://5d559397bae39100201eedc1-copobndjap.chromatic.com/?path=/story/all-components-card--default)
- [LegacyCard](https://5d559397bae39100201eedc1-copobndjap.chromatic.com/?path=/story/all-components-legacycard--default)
- [Banner](https://5d559397bae39100201eedc1-copobndjap.chromatic.com/?path=/story/all-components-banner--default)
- [BulkActions](https://5d559397bae39100201eedc1-copobndjap.chromatic.com/?path=/story/all-components-indextable--with-bulk-actions) (IndexTable)
- [Popover](https://5d559397bae39100201eedc1-copobndjap.chromatic.com/?path=/story/all-components-popover--all)
- [Tooltip](https://5d559397bae39100201eedc1-copobndjap.chromatic.com/?path=/story/all-components-tooltip--all)
- [Toast](https://5d559397bae39100201eedc1-copobndjap.chromatic.com//?path=/story/all-components-toast--default)

👀 [Full list of visual diffs](https://shopify.chromatic.com/build?appId=5d559397bae39100201eedc1&number=21802) (note: the bevel on examples look different in the Chromatic diff than they do on Storybook)
📖 [Storybook](https://5d559397bae39100201eedc1-copobndjap.chromatic.com/)

## Screenshots

<details>
<summary>Index Table (original related issue)</summary>
index-table
</details>

<details>
<summary>Banner</summary>
banner
</details>

<details>
<summary>Bulk actions</summary>
bulk-actions
</details>

<details>
<summary>Card small screen (no border radius)</summary>
card-small
</details>

<details>
<summary>Card</summary>
card
</details>

<details>
<summary>Popover</summary>
popover
</details>

<details>
<summary>Toast</summary>
toast
</details>

<details>
<summary>Tooltip</summary>
tooltip
</details>

> [!NOTE]
> This isn't the full implementation. There is still further clean up that and testing to be done. This is only for visual review purposes.

### CODE REVIEW

**Comment by sam-b-rose** [comment]
@sarahill can you inspect the tooltip for this change? 🙏 I know Aaron and you working on getting the details refined.

**Comment by tjonx** [comment]
> Banner
> banner

The bevel should affect the blue color and the interior color of the cards. This implementation makes it look like a border and kills the concept of a bevel, unfortunately.

**Comment by sarahill** [comment]
➕ to what @tjonx said. The border starts to make it feel "fuzzy" and does lose the bevel effect all together. Were there other alternatives explored? I'm all for simplifying the bevels but it would be nice to maintain the bevel effect.

**Pull request closed without merging**
