### PR TITLE
[polaris.shopify.com] Add component sections

### LINKED ISSUE #7421: [Layout foundations] [Beta] Add component groups and overview pages in the navigation
Add component groups and overview pages in the navigation.
[**Figma file**](https://www.figma.com/file/5oEi1wm73KhGLN0VS02oYm/Layout-components?node-id=3319%3A43022&t=0kLdab20gmQpthZV-4)

---

**Groups:**
- [**See Figma file for details**](https://www.figma.com/file/5oEi1wm73KhGLN0VS02oYm/Layout-components?node-id=3319%3A43022&t=f3R41ouqedXat1KA-4)
- Actions
- Layout and structure
- Selection and input
- Images and icons
- Feedback indicators
- Typography
- Tables
- Lists
- Navigation
- Overlays
- Utilities
- Deprecated

---

Proposed

---

https://github.com/Shopify/polaris/issues/7421#tasklist-block-2f35e8ef-60b0-4572-90e5-3a3e35dae318

### PR DESCRIPTION
**Pull request by kyledurand**
image

There are still a couple of outstanding items from https://github.com/Shopify/polaris/issues/7421 like creating manual redirects and adding related items but I think this deserves an early start in the review process 🙏 

### Tophatting

Feel free to only 🎩 within your area of expertise

[Staging](https://polaris-staging.shopifycloud.com/)

Closes: https://github.com/Shopify/polaris/issues/7421

### CODE REVIEW

**Review by laurkim — APPROVED** [review]
🚀 💯 :shipit:

**Comment by sarahill** [comment]
Overall looks good. Couple small nit picky things. 
- Can we increase the margin between groups to `16px` instead of `8px`?
- Can the group headings be the darker text color? So "Layout and structure" would be slightly darker than the component names

We can follow-up with these things in separate issues

**Review by sarahill — APPROVED** [review]

**Review by aveline — APPROVED** [review]

**Pull request merged**
