### PR TITLE
Adjust link and plain button focus ring

### PR DESCRIPTION
**Pull request by aveline**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-summer-editions/issues/613

### WHAT is this pull request doing?

Updates focus styles for links and plain button
Screenshot 2023-07-10 at 9 01 13 AM
Screenshot 2023-07-10 at 9 00 06 AM
Screenshot 2023-07-10 at 8 59 04 AM
Screenshot 2023-07-10 at 8 57 03 AM
Screenshot 2023-07-07 at 10 42 15 AM

### How to 🎩
Review in spin https://admin.web.web-j07b.aveline-thelen.us.spin.dev/store/shop1

### CODE REVIEW

**Review by sarahill — APPROVED** [review]

**Review by sam-b-rose — APPROVED** [review]
Looks like we do have a `--p-border-radius-1_5-experimental` token which is `6px`. Could we use that for these radius values?

**Pull request merged**
