### PR TITLE
(Polaris icons) Adds dynamic sources icons

### PR DESCRIPTION
**Pull request by Rusty-UX**
Note this PR replaces the [original PR](https://github.com/Shopify/polaris/pull/7040) by @gil-- to add the icons. This PR adds the appropriate sized icons and variations.

image

image

### WHY are these changes introduced?
Adds support for dynamic source iconography in Polaris. Currently used within the theme editor. By adding these icons to polaris, 3rd party app developers can leverage these icons.

### WHAT is this pull request doing?
Adds support for:
- Dynamic source major
- Dynamic source minor
- Insert dynamic source major
- Insert dynamic source minor

github-icons

@alex-page I've checked the format/paths, but if you can you please double check to make sure the SVG paths are clean that would be appreciated. Also, I'm not sure what's happening with the changelog error, any idea what might be causing that?

cc @gil-- @leileu

### CODE REVIEW

**Comment by ghost** [comment]
👋 Thanks for opening your first pull request. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by gil--** [comment]
@Rusty-UX Thank you for adding them!! ❤️

**Review by alex-page — APPROVED** [review]

**Comment by alex-page** [comment]
@Shopify/polaris-team can someone take a look at fixing the SVG attributes in this PR. Everything else looks good to me.

**Comment by kyledurand** [comment]
What's up @Rusty-UX! I'm going to take a crack at fixing up the checks here

**Review by kyledurand — APPROVED** [review]

**Pull request merged**
