### PR TITLE
[Modal] Add `flex-grow` to `Modal` body to fix footer position

### LINKED ISSUE #11185: [Modal]: When prop `size="fullScreen"`, there's a funky UX BUG 🐛
There's a really funky bug 🐛 when the **[prop `size` on Modal](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/Modal/Modal.tsx#L47)** is `"fullScreen"`. 

See video:

https://github.com/Shopify/polaris/assets/43223543/075337d9-c30a-4a5e-885e-111687c012a7

## Steps to reproduce the problem

1. Go to any component that is consuming the Modal
2. Make the screen smaller
3. Notice how the footer is strangely large and consumes most of the screen 🤔 😢

### PR DESCRIPTION
**Pull request by yurm04**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris/issues/11185 

Before

https://github.com/Shopify/polaris/assets/4642404/8afa1dc4-7193-4616-8537-bbe86db9168f

After

https://github.com/Shopify/polaris/assets/4642404/c463c9e7-14e5-4edd-be65-430e69abb19d

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [ ] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by ginabak — COMMENTED** [review]
Hiii!! Happy new year 🥳 ❤️ Thanks for your patience with the review! I was away in Dec for a week 😄. 

I used the snapshot on my **[spin link](https://admin.web.order-edit-refactor.gina-bak.us.spin.dev/store/shop1/draft_orders/new)**, and I'm still seeing the same thing for product resource picker ... 🤔 I'm not sure if it's spin, so I tried it on a couple instances and did `dev up` and `dev refresh`, but still getting this behaviour?

https://github.com/Shopify/polaris/assets/43223543/16345928-8db8-4723-bba1-5cfe9c593af9

**Comment by yurm04** [comment]
@ginabak thanks for reviewing! I dug into the `ResourcePicker` and [found out that it has `noScroll` set for the modal](https://github.com/Shopify/web/blob/bc5aff81b455b3b5fe4b41438bf62466cc16d47f/app/shared/components/ResourcePicker/ResourcePicker.tsx#L796). In Polaris, the `noScroll` markup is different and wasn't getting the same styling applied to address this issue. I've addressed both now, but I could use your help with QAing this in the admin. Things look good in the polaris storybook, but I'm not sure if this change could have weird side effects elsewhere 🙏

**Review by ginabak — COMMENTED** [review]
Hiii Yuraima! Nice catch on the no scroll. THANK YOU! 🥳 YAY, can see the changes on the the resource picker! I'll do my best to tophat as much as I can in the admin - but had a couple more UX questions, that I guess could be addressed later 😄, but got me curious: 

1) Are we okay with a lot of white space when the content in the modal is shorter  --- I guess in the correct place now? 

My first instinct felt off, but I guess this is better than it was before 😄: 

| BEFORE | AFTER |
|--------|--------|
| BEFORE - short content | AFTER - with short content  |


2) Not sure if this is particular to the resource picker or if this is a modal thing, but is there a reason we don't "adjust" the size of the modal when there isn't a lot of content, but then we do resize it sometimes? 

| RESIZED | NOT RESIZED - LOTS OF WHITESPACE |
|--------|--------|
| No white space modal size resized to content | White Space |

**Comment by yurm04** [comment]
Thanks for your comments @ginabak :)

1. I think this solution brings us back to parity with the original implementation of Modal before we migrated to using layout components ([see @chloerice's comment on the issue](https://github.com/Shopify/polaris/issues/11185#issuecomment-1854212525)). @heyjoethomas [did have similar feedback in another comment](https://github.com/Shopify/polaris/issues/11185#issuecomment-1847923448) so he can weigh in here now that we have a proposed solution. This PR would fix the bug, but if the original UX was not ideal to begin with and that's a blocker, we should go back to the drawing board. If it's not a blocker, I think we can ship this and have a broader discussion about mobile modal behaviors.

2. I'm not sure why these two different modals don't resize in the same way 🤔  According to the modal CSS, the modal height [should fit the content up to a `max-height`](https://github.com/Shopify/polaris/blob/5604728ee1a117f29e0450b354ea46f44506c74f/polaris-react/src/components/Modal/components/Dialog/Dialog.module.scss#L42). Can you send a link in the code to these two modals? It may be something with how they're implemented, but I won't know for sure until I can play around with it myself.

**Review by ginabak — APPROVED** [review]
Hiiiiii! Thanks so so much for answering my questions! I'm approving as this solution will fix the bug 🐛. It's a significant improvement over the existing whitespace at the bottom of the footer. 😅 

I'm interested to hear what @heyjoethomas thinks about the full-screen whitespace issue, as discussed [here](https://github.com/Shopify/polaris/pull/11354#pullrequestreview-1810313958).

Aaaand, here's a [link to my spin](https://admin.web.polaris-testing.gina-bak.us.spin.dev/store/shop1/draft_orders/new) that includes the most recent snapshot of this PR. 😄 ❤️ I think the modal resizing can be addressed in a separate PR, but I am curious why the resizing happens so differently!

**Comment by chloerice** [comment]
> Not sure if this is particular to the resource picker or if this is a modal thing, but is there a reason we don't "adjust" the size of the modal when there isn't a lot of content, but then we do resize it sometimes?

Modals resize based on their content's height up until it reaches the max-height (`100vh - 3.75rem`) unless they're composed with a fixed height container wrapping the contents. Some implementations do this to prevent resize jank and some unfortunately don't. It's super jolting and uncrafted for it to resize every time merchants begin typing to filter a list for example, especially when they're not even done typing 🫨. If the desire in your team's use case is for the modal to grow and shrink with its contents, then using the `fullscreen` variant is blocking the UX from functioning the way you want it to because it's meant to stop the modal from resizing on small screen.

**Comment by heyjoethomas** [comment]
> Are we okay with a lot of white space when the content in the modal is shorter --- I guess in the correct place now?

Yes. The actions fixed at the bottom are much better. This is how something that has been declared fullscreen should work. It keeps actions in a consistent location and keeps the general component anatomy consistent.

**Comment by yurm04** [comment]
Thanks all for your input! Will merge this in when the next release goes out

**Review by heyjoethomas — APPROVED** [review]

**Comment by lgriffee** [comment]
This PR was reverted due to regressions found in prod. 

- https://github.com/Shopify/polaris/pull/11436
- https://github.com/Shopify/web/pull/114385

**Pull request merged**
