### PR TITLE
Add support for replacing custom properties in at-rules

### PR DESCRIPTION
**Pull request by aaronccasanova**
This PR updates the generic `styles-replace-custom-property` migration to support replacing custom properties in `atRules`. With this change, the structure of the `replacementMaps` has been updated to include dedicated keys for `decls` and `atRules`, and introduces new/associated CLI flags (e.g. `--atRule`, `--atRuleIdentifier`, and `--namespace`).

Example with CLI:
```sh
npx @shopify/polaris-migrator styles-replace-custom-property \
  --namespace="legacy-polaris-v8" \
  --decl="fill" \
  --atRule="include" \
  --atRuleIdentifier="fill-icon,recolor-icon" \
  --from="--p-icon" \
  --to="--p-color-icon" \
  "**/*.scss"
```

Example with `replacement-maps.js`:
```js
// npx @shopify/polaris-migrator styles-replace-custom-properties \
//   --namespace="legacy-polaris-v8"
//   --maps="./replacement-maps.js"
//   "**/*.scss"
const fillMap = {'--p-icon': '--p-color-icon'}
export default {
  decls: {fill: fillMap},
  atRules: {
    include: {
      'fill-icon': fillMap,
      'recolor-icon': fillMap,
    }
  },
}
```

### CODE REVIEW

**Review by lgriffee — APPROVED** [review]
This is going to be so useful! 💯🚢✨🎉

**Review by alex-page — APPROVED** [review]

**Comment by aaronccasanova** [comment]
Mixins are being removed in waves, which eliminates the need for this added behavior.

**Pull request closed without merging**
