### PR TITLE
[Layout foundations][Batch 2] Rebuild components with layout primitives

### PR DESCRIPTION
**Pull request by laurkim**
### WHY are these changes introduced?

Related to [7565](https://github.com/Shopify/polaris/issues/7565).

### WHAT is this pull request doing?

Rebuilds the following components to use our layout primitives.
- `ResourceItem` #7580  
- `ActionList` #7458  
- `SkeletonPage` #7714  
- `EmptyState` #7564

Fixes
- https://github.com/Shopify/polaris/issues/8078

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by chazdean — APPROVED** [review]
LGTM ✅

**Comment by sarahill** [comment]
seeing an issue with space for bulk actions showing up when no bulk actions present. Also, generally feels weird that the actions add whitespace to the table in general but I'm guessing that was an intentional decision and should be addressed separately?

**Review by sarahill — APPROVED** [review]
Looks good! The chromatic diffs for skeleton page look off but they look fine in storybook so I left them but I think this is good to go

**Review by aveline — APPROVED** [review]

**Review by yurm04 — APPROVED** [review]
🚢

**Review by nayeobkim — APPROVED** [review]

**Review by chazdean — APPROVED** [review]

**Review by sarahill — APPROVED** [review]

**Review by kyledurand — APPROVED** [review]
This looks pretty solid. Only thing I'm seeing is a slight difference in spacing on empty state. That could be intentional though
es

**Pull request merged**
