### PR TITLE
fix(polaris-tokens): :bug: Export types missing for the Typescript Compiler (tsc) when using Node16/Bundler Module Resolution.

### LINKED ISSUE #10601: After importing `polaris-react` into my project, my App's `tsc` type check fails.
## Issue summary

Hi there, I'm on `polaris@11.19.0`, but when I run a `tsc` (Typescript compiler) on my app, I'm getting the following error:
```
node_modules/@shopify/polaris/build/ts/src/utilities/use-theme.d.ts:408:44 - error TS2307: Cannot find module '@shopify/polaris-tokens/dist/types/src/themes/types' or its corresponding type declarations.

408 export declare function useTheme(): import("@shopify/polaris-tokens/dist/types/src/themes/types").ExtractMetaThemeValues<{
```
I do have `compilerOptions.skipLibCheck` set to `true` in my App's `tsconfig.json`, and if I turn that off, I can workaround this issue, but it's not ideal.  The issue seems to be due to `ExtractMetaThemeValues` and `MetaTokenProperties` not being exported from `polaris-tokens`, and `polaris-react` is trying to reach directly into the non-exported type, which is fine for `rollup` (which seems to be `polaris`'s builder), but not for `tsc`.

Another workaround I found was to set the following values in my `tsconfig.json`, which fixes the pathing issue:
```
{
  "compilerOptions": {
    "skipLibCheck": false,
    "paths": {
      "@shopify/polaris-tokens/dist/types/src/themes/types": ["node_modules/@shopify/polaris-tokens/dist/types/src/themes/types.ts"],
    }
  }
}
```

A true solution I've found is to set the [following lines](https://github.com/Shopify/polaris/blob/main/polaris-tokens/src/index.ts#L11) in `polaris-tokens` to:
```
export type {
  ThemeName,
  Theme,
  ExtractMetaThemeValues,
  MetaTokenProperties,
} from './themes/types';
```
which changes the built path to a correct value.  I'll open a PR with the above fix, where we can discuss if this is the approach you want to go with.

## Expected behavior

I should be able to import `polaris` into my app, and compile my Typescript types with `compilerOptions.skipLibCheck = false`.

## Actual behavior

When running `tsc`, I get the following:
```
node_modules/@shopify/polaris/build/ts/src/utilities/use-theme.d.ts:408:44 - error TS2307: Cannot find module '@shopify/polaris-tokens/dist/types/src/themes/types' or its corresponding type declarations.

408 export declare function useTheme(): import("@shopify/polaris-tokens/dist/types/src/themes/types").ExtractMetaThemeValues<{
```

## Steps to reproduce the problem

1. Install `polaris` into Typescript app.
2. Make sure `compilerOptions.skipLibCheck` in the app's `tsconfig.json` is set to `false`.
3. Run `tsc`.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 11.19.0

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
  System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (2) x64 Intel(R) Xeon(R) CPU @ 2.60GHz
    Memory: 11.70 GB / 15.61 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/src/github.com/Shopify/polaris/node_modules/.bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
```

### PR DESCRIPTION
**Pull request by patrickDouglas**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris/issues/10601

### WHAT is this pull request doing?

Export types missing for the Typescript Compiler (tsc) when using Node16/Bundler Module Resolution.

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)
I may need help, since this is more of a compile issue for library users.

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by jesstelford — APPROVED** [review]
Since this type is being used in an external module, it makes sense that it's exported here 👍 

@patrickDouglas you'll need to add a changeset with `yarn changeset`, then select `@shopify/polaris-tokens` and `patch`.

**Comment by patrickDouglas** [comment]
> you'll need to add a changeset with `yarn changeset`, then select `@shopify/polaris-tokens` and `patch`.

@jesstelford When I'm running `yarn changeset`, it's not giving me the chance to select `patch`.  It's forcing a major release?  Maybe we can 🍐 tomorrow?
```
꩜  ~/src/github.com/Shopify/polaris tokens-modern-type-export % yarn changeset                   polaris-ume1
yarn run v1.22.17
$ changeset
🦋  Which packages would you like to include? · @shopify/polaris-tokens
🦋  Which packages should have a major bump? … 
◯ all packages
  ◯ @shopify/polaris-tokens@7.9.0
  ```

**Comment by patrickDouglas** [comment]
> Since this type is being used in an external module, it makes sense that it's exported here 👍

@jesstelford `Template` is the type that being used by an external module (it's being used by `polaris-react`, which is being used by my team's app).  The `Template` type uses the types that need to be exported, but when the library is built, the imports for the types are using a file path that's not defined in the `package.json`, and TS's Node16 Module Resolution respects that (as it should).

**Comment by patrickDouglas** [comment]
@jesstelford Any thoughts on why I can't do a patch release with changesets?

**Comment by sam-b-rose** [comment]
> it's not giving me the chance to select `patch`

The CLI prompt is confusing. Using <kbd>Space</kbd> selects the item and pressing <kbd>Enter</kbd>.

Hit <kbd>Enter</kbd> twice to skip selecting `major` then skip `minor`. `patch` will be selected as the default.

**Review by jesstelford — APPROVED** [review]

**Pull request merged**
