### PR TITLE
[Button] Update `micro` button height and padding

### PR DESCRIPTION
**Pull request by sophschneider**
### WHY are these changes introduced?

Fixes [this issue](https://github.com/Shopify/polaris-summer-editions/issues/1018)

### WHAT is this pull request doing?

For micro not icon only buttons:
* padding: `6px 8px` -> `4px 8px`
* min-height: `28px` -> `24px`
* weight: `semi-bold` -> `bold`
* revert changes to slim from [this PR](https://github.com/Shopify/polaris/pull/9809/files)

Note that the micro button still grows with its container, so if it is in a horizontal stack with elements taller than 24px, the micro button will take the height of the container.

To mitigate this, you can wrap the micro buttons in a div, like I did in the story. Thankfully, `IndexFilters` is already implemented with wrapping divs

<details>

<summary>before/after</summary>

|Before|After|
|-|-|
|Screenshot 2023-07-24 at 5 52 41 PM|Screenshot 2023-07-24 at 5 52 35 PM|

|Before|After|
|-|-|
|Screenshot 2023-07-24 at 5 34 50 PM|Screenshot 2023-07-24 at 5 35 04 PM|

</details>

### How to 🎩

* [Micro button story](https://5d559397bae39100201eedc1-sqzlnljcvi.chromatic.com/?path=/story/all-components-button--micro&globals=polarisSummerEditions2023:true)
* [IndexFilters story](https://5d559397bae39100201eedc1-sqzlnljcvi.chromatic.com/?path=/story/all-components-indexfilters--with-pinned-filters&globals=polarisSummerEditions2023:true)
* [Index table filters in web](https://admin.web.web-6m3n.sophie-schneider.us.spin.dev/store/shop1/orders?inContextTimeframe=last_30_days)
* [Slim button story](https://5d559397bae39100201eedc1-sqzlnljcvi.chromatic.com/?path=/story/all-components-button--slim&globals=polarisSummerEditions2023:true)

### CODE REVIEW

**Review by sarahill — APPROVED** [review]

**Review by laurkim — APPROVED** [review]

**Comment by sophschneider** [comment]
There are some cases in the admin where the slim button looks quite tight (see [date pickers on marketing](https://admin.web.web-6m3n.sophie-schneider.us.spin.dev/store/shop1/marketing?attributionModel=last_click_non_direct)). Just double checking that this is ok, we may want to wait a week to merge this to avoid regressions

**Comment by sophschneider** [comment]
@sarahill @laurkim I've updated the changes in height to `micro` instead of `slim` to minimize regressions in web! I've also reverted the changes from the [original slim (shady) PR](https://github.com/Shopify/polaris/pull/9809/files)

**Review by sarahill — APPROVED** [review]
This looks good to me! Keeping the slim buttons is feeling better too for the context they're used in.

**Pull request merged**
