### PR TITLE
[Polaris website refresh] Add `Contributing` section

### PR DESCRIPTION
**Pull request by yurm04**
This PR adds a `Contributing` section to the new website for housing the new contribution guidelines 🚀 
* Nav link in the top bar nav
* Contributing index page with left nav
  * Subpages with page level table of contents on the right 

Screen Shot 2022-06-14 at 10 47 07 PM

### CODE REVIEW

**Comment by heyjoethomas** [comment]
We should add a page about updating Icons. That is a super common question in Slack.

**Review by romellogoodman — APPROVED** [review]
lgtm!

**Comment by heyjoethomas** [comment]
Also, maybe the nav label could be "Figma UI Kit". I think seeing the word Figma in there would really make it clear what we are referring too. Thoughts?

**Comment by selenehinkley** [comment]
We will need the ability to add a 6 column table to each contribution type section. Any issues in doing this? Marten has designed a 5 column table for tokens so I'm thinking it won't be a problem.

Screen Shot 2022-06-08 at 7 43 52 AM

See all tables in the [draft content doc](https://docs.google.com/document/d/1ydNQA4vFq2MWV3EtPpg87nyUoRNm
)

image

**Comment by selenehinkley** [comment]
@heyjoethomas used this [visual treatment](https://www.figma.com/file/mMHFt3kEDNjLMZWowi6gnt/branch/vMQUveoCXr4p5UwIQOGfh6/Polaris-Icons) to direct the reader to where they can find support. Thinking we could try this throughout the doc and see how it looks.
Screen Shot 2022-06-10 at 12 54 41 PM

**Comment by selenehinkley** [comment]
Adding the link to the [images](https://www.figma.com/file/AmWrEvFtsIhX314gfqsgrx/Perfect-vs.-Consistent?node-id=0%3A1) we'll be using in the documentation.

**Comment by chloerice** [comment]
This PR is ready to bring the content over from the Google doc ✅

**Pull request merged**
