### PR TITLE
Update dark experimental theme for top bar buttons

### PR DESCRIPTION
**Pull request by sophschneider**
### WHY are these changes introduced?

Part of https://github.com/Shopify/polaris-backlog/issues/1573

### WHAT is this pull request doing?

Updates from [this figma](https://www.figma.com/file/pGwkMhydM8nURjBRHo9GVh/Dark-UI-Lab?type=design&node-id=22078%3A19050&mode=design&t=IlsqiSZUSTqhC5Bl-1) for the `dark-experimental` theme

### How to 🎩

Check out new tokens consumed in the top bar. Open the user menu to see new divider color and white alphas

https://admin.web.web-minimal-m4pm.sophie-schneider.us.spin.dev/store/shop1

### CODE REVIEW

**Review by kyledurand — APPROVED** [review]
🎩 looks great

**Review by laurkim — APPROVED** [review]
Nice 💯 👏

**Review by sam-b-rose — APPROVED** [review]
Looks good! ❇️

**Review by aaronccasanova — APPROVED** [review]

**Pull request merged**
