### PR TITLE
add `inlang` to make the contribution of translations easier

### PR DESCRIPTION
**Pull request by NilsJacobsen**
Let me know what changes you request for merging this PR.

### Description
This pull request adds the possibility for contributors and translators to manage translations in a UI instead of files with no overhead for the maintainers.

To get a UI for translations contained in this repository, an [inlang.config.js](https://inlang.com/documentation/config) has been created at the root of the repository.

### Preview
The changes of this PR and a live instance of the editor can be previewed with the following link https://inlang.com/editor/github.com/NilsJacobsen/polaris. Note: This link should be changed to point to polars instead of NilsJacobsen after this PR has been merged.

### Limitations
**Certain actions are slow**
Inlang is running entirely on git, giving tremendous CI/CD and contribution power to localization (and potentially other verticals -> [the next git](https://www.youtube.com/watch?v=vJ3jGgCrz2I)). That means that the whole polaris repo is cloned into the browser which makes certain actions like the initial load and pushing changes slow. Those limitations will be fixed with future releases and require no input from polaris.

pika-1680686287719-1x

### Badge
If you want to show the contributor the status of the translations, you could add a badge to your readme.
```
[![translation badge](https://inlang.com/badge?url=github.com/NilsJacobsen/polaris)](https://inlang.com/editor/github.com/NilsJacobsen/polaris?ref=badge)
```

Preview the messages on https://inlang.com/github.com/NilsJacobsen/polaris .

### CODE REVIEW

**Comment by NilsJacobsen** [comment]
@sophschneider I saw you opened an issue that deals with i18n. https://github.com/Shopify/polaris/issues/9090

**Comment by sophschneider** [comment]
Hi @NilsJacobsen, thanks for contributing to Polaris! We currently have our own in house translation platform at Shopify as seen in this [PR](https://github.com/Shopify/polaris/pull/8777) that manages translations, creates a CI step for them, and sends them to be translated for us. Is there any advantage to inlang vs. just editing the json files directly? Just curious about the workflow for using it because I took a quick look and found it a little bit harder to read than the json files themselves

**Comment by NilsJacobsen** [comment]
@sophschneider thanks for your replay and that you take the time to really understand inlang and inlang's advantages.

>At first a disclaimer: There is no need to replace something. Inlang is just a configuration file, works with any setup and alongside other i18n solutions.

Workflow:
- Dev creates demand for translations in the code, for example by adding ui
- Contributor clicks on inlang link, sorts language and missing messages (to get todo list view)
- Does translations
- Frontend works like vs code (commit, push, PR)

What would you consider a great editor? What are you thinking?

### Advantage of the inlang editor over code:
- Grouping by message (easier to translate)
- Linting -> use standard lint rules or write your own, see what needs to be changed/what's wrong directly in the editor, soon also available as a CI step
- Machine translations
- Variables/placeholder support

### Advantage of inlang itself
- no need to maintain your internal solution
- It's just a config file that allows you to connect to inlang's editor and vs code extension (release in two weeks), Automations -> CI (soon).

>Actually, it should be a no brainer. At best you get more language contributions and at worst you just added a config file. Nothing to maintain.

**Comment by sophschneider** [comment]
I'm going to close this PR since we already have a translations platform at Shopify that handles all translation management (including sending strings to translators and CI checks) and we have a config file `translations.yml` for it. We also don't have that many strings and typically do not have external contributions for our translations. Adding a second translations config seems redundant.

**Pull request closed without merging**
