### PR TITLE
Sunset `Space` page

### PR DESCRIPTION
**Pull request by aveline**
Remove the `Space` page from the website

### CODE REVIEW

**Review by jesstelford — CHANGES_REQUESTED** [review]
Needs a redirect to some other page, or if there's no equivalent, a placeholder page which describes where the docs have gone. Otherwise our builders will be left confused and lost if they're following an old link / bookmark / open tab / etc.

**Comment by tjonx** [comment]
> Needs a redirect to some other page, or if there's no equivalent, a placeholder page which describes where the docs have gone. Otherwise our builders will be left confused and lost if they're following an old link / bookmark / open tab / etc.

This will be redirected to the new Layout page.

**Review by jesstelford — APPROVED** [review]
I went ahead and added the redirect 👍

**Comment by jesstelford** [comment]
Unsure why CI is failing here... That issue with the `_` should have been resolved in https://github.com/Shopify/polaris/pull/10863 🤔

**Review by yurm04 — APPROVED** [review]

**Pull request merged**
