### PR TITLE
[Stylelint plugin] Overridable options for polaris/coverage rule

### PR DESCRIPTION
**Pull request by jesstelford**
## Background

The `@shopify/stylelint-polaris` Stylelint plugin provides the `polaris/coverage` rule (among other things). This rule is a kind of _mini-plugin_ inside the rule because it executes a whole bunch of other rules that are passed in via config.

### Example 1: Internal

For example, the current internal-only config for `polaris/coverage`:

```javascript
{
  border: [
    {
      'polaris/at-rule-disallowed-list': {
        include: [
          'focus-ring',
          'no-focus-ring',
        ],
      },
    },
    {
      message: 'Please use a Polaris border token',
    },
  ]
}
```

disallows the use of `@focus-ring` and `@no-focus-ring` mixins with a custom message prefix of `Please use a Polaris border token`.

This config results in error messages like:

```
  2:3  ✖  Unexpected @mixin rule "focus-ring base, 100px" - polaris/border/polaris/at-rule-disallowed-list
          Please use a Polaris border token - https://polaris.shopify.com/tools/stylelint-polaris/rules/border-at-rule-disallowed-list
```

### Example 2: web

Web is currently overwriting rules by [reaching deeply into the config object and modifying it](https://github.com/Shopify/web/blob/main/.stylelintrc.js#L4-L10) which is brittle at best. This PR now makes it possible to do pass proper config instead:

```diff
-const stylelintPolarisConfig = require('@shopify/stylelint-polaris');
-
-const polarisCoverageConfig = stylelintPolarisConfig.rules['polaris/coverage'];
-polarisCoverageConfig['media-queries'][0]['polaris/media-query-allowed-list'] =
-  {
-    disabled: true,
-  };
-
 module.exports = {
   extends: [
     'stylelint-config-standard',
@@ -220,7 +210,16 @@ module.exports = {
     {
       files: ['**/*.css'],
       rules: {
-        'polaris/coverage': polarisCoverageConfig,
+        'polaris/coverage': [
+          true,
+          {
+            'media-queries': {
+              'polaris/media-query-allowed-list': {
+                disabled: true,
+              },
+            },
+          },
+        ],
       },
     },
```

## Context

The above config and output are fine in 99% of cases, but we also use the `polaris/coverage` rule internally within our own codebase (`@shopify/polaris`), where we _do_ have a mixin called `@focus-ring` that we _do_ want to us.

Unfortunately, that means our codebase is now littered with pointless rule disables:

```sass
  // stylelint-disable-next-line -- generated by polaris-migrator DO NOT COPY
  @include focus-ring;
```

## The change

This PR retains all the existing config, so no rules change, but enables consumers of the plugin / rule to either fully overwrite the config, or merge in alterations the config (via Stylelint's "secondary options" parameter):

```javascript
// .stylelintrc.js
module.exports = {
  extends: ['@shopify/stylelint-polaris'],
  overrides: [
    {
      files: ['polaris-react/*.css'],
      rules: {
        'polaris/coverage': [
          true,
          {
            border: [
              {
                // We're allowed to use mixins internally in our own codebase
                'polaris/at-rule-disallowed-list': null,
              },
            ],
          },
        ],
      },
    },
  ],
}
```

This will enable us to clean up a lot of the needless `stylelint-disables` throughout the codebase and be more targeted in what rules apply where.

### CODE REVIEW

**Review by gwyneplaine — APPROVED** [review]
lgtm, granted that's because I'm philosophically aligned on disabling these rules in polaris. While I can imagine logical reasons for not wanting to do this, I think being able to do do this is a net good 👍

**Comment by aaronccasanova** [comment]
**Initial thought:** I'm hesitant to reduce this much friction for disabling rules.

The [original architecture](https://github.com/Shopify/polaris/pull/5331) provided `shared`, `internal`, and `external` configs. They were consolidated [here](https://github.com/Shopify/polaris/issues/7542), but I wonder if we should reintroduce them instead? cc @alex-page Thoughts?

**Comment by jesstelford** [comment]
I'm not sure I understand the benefit of splitting `shared`, `internal`, and `external` configs - having it as a single set of defaults makes sense to me.

From #7542, I can understand the desire to enforce the rules, but I disagree with the examples given;

> `--pc-mt: var(--p-space-2)` is not good, the token should do the work here. Replace `--pc-mt` with `--p-space-2`
> `--pc-mt: 11px` is even worse. As it is hiding off mainline rules.

The custom property name `mt` here isn't useful, agreed. However, there are many uses of custom properties for giving values names that are specific to a component which make the code _better_ but are not specific to our token library (and nor should they be). Some examples from our current code:

```css
/* Popover */
--pc-popover-visible-portion-of-arrow: 5px;

/* Color Picker */
--pc-color-picker-size: 160px;
--pc-color-picker-vertical-border-radius: calc(var(--pc-color-picker-size) * 0.5);

/* ResourceList */
--pc-resource-list-stacking-order: 1;

/* Badge */
--pc-pip-size: var(--p-space-200);
```

All of these either give a concrete name to an otherwise "magic" number, or are used in multiple places ensuring that if the value ever needs to change, it will correctly propagate to each usage site without having to guess / search for them all.

I'm unsure why we'd ever want to disallow Custom Property usage tbh; it'd be like saying "All component JavaScript must now be written with _no_ variables; `const` is now a lint error." Our codebase would be worse off if we tried that, but in practical terms we'd just end up with 1000's of `// eslint-disable-next-line` (and... surprise; we have over 1000 instances of `stylelint-disable` in our codebase today 😓)

---

Regardless, I've updated the PR description with 2 concrete use cases for allowing the config to be partially overwritten. Hopefully that helps clarify.

**Comment by alex-page** [comment]
The objective is to not have these mixins. The comments are intentional in `shopify/polaris` and show our current technical debt. We shouldn't aim to remove these comments we should aim to fix the root cause which is mixins scaling code.

**Comment by aaronccasanova** [comment]
> The comments are intentional in `shopify/polaris` and show our current technical debt. We shouldn't aim to remove these comments we should aim to fix the root cause which is mixins scaling code.

Exactly this. We use the stylelint-disable comments and descriptions as data points to evolve the system. I think removing friction at this layer hinders our ability to assess off mainline code and introduces a mechanism that will slowly cause mismatches/divergences between stylelint runs and the coverage site.

> I'm not sure I understand the benefit of splitting `shared`, `internal`, and `external` configs - having it as a single set of defaults makes sense to me.

For sure, I think there are multiple ways to approach the problem. I see split configs roughly the same as defaults with overrides. However, split configs would maintain the friction we established for consumers attempting to override our rules. Alternatively, if that perspective is changing and we will now allow consumers to override coverage rules from their configs, I think there are other patterns to explore that don't require refactoring the `polaris/coverage` plugin options. For example introducing a `extendPolarisCoverage` utility e.g.
```js
import {extendPolarisCoverage} from '@shopify/stylelint-polaris'

export default {
  plugins: ['@shopify/stylelint-polaris/coverage'],
  rules: {
    'polaris/coverage': extendPolarisCoverage({
      color: {
        'my-rule': null
      }
    })
  }
}
```

Again, this still feels like a paradigm shift from what we have today.

> Also, it's important to note the `coverage` plugin options were designed to be agnostic of Polaris. It's simply a plugin that allows consumers to categorize rules. Anyone can technically pull in `stylelint-polaris` and categorize rules around their system (e.g. using naming conventions from tailwindcss, open-props, and so on).

All that said, I hope this isn't blocking the Sass to CSS initiative. Cleaning up stylelint-disable comments and increasing coverage is usually associated with a Vault project. If it is blocking, I suggest leaving the existing stylelint-disable comments in Polaris until we have alignment.

**Comment by jesstelford** [comment]
> I hope this isn't blocking the Sass to CSS initiative.

Unfortunately it is.

The alternative is disabling the stylelint `polaris/coverage` rule _entirely_ for the `polaris-react/postcss-mixins` folder which feels much worse to me.

But given the above comments, this isn't a hill I care about, let alone one I want to die on, so I'll just go ahead and disable it entirely for the folder.

_Edit_: And if we care that deeply about rules not being disabled, then we might want to [do something about this disabled rule in `web`](https://github.com/Shopify/web/blob/main/.stylelintrc.js#L4-L10).

**Pull request closed without merging**
