### PR TITLE
[Popover] Add cover position

### PR DESCRIPTION
**Pull request by kyledurand**
Closes: https://github.com/Shopify/polaris-internal/issues/1445

https://github.com/Shopify/polaris/assets/6844391/712fe5c9-d07e-48d7-968e-5207a3b582a3

[Figma](https://www.figma.com/file/I3df2veCGRVUuxzpXVE71m/Pickers?type=design&node-id=1655%3A23178&mode=design&t=TRgQMY4IDT6gbY8Y-1)

### CODE REVIEW

**Review by sophschneider — APPROVED** [review]
Changes look good! I didn't tophat, should we add a story or is this for a specific picker pattern edge case?

This PR will for sure conflict with HoverCard a bit so probably best to wait for eyes from Yurms or Chloe

**Comment by kyledurand** [comment]
It's a pretty bespoke pattern that I'm not sure we need to advertise with stories just yet, but the snapshots will be useful when we get closer to shipping the new picker.

I let Chloe know about this [yesterday](https://shopify.slack.com/archives/C05BFAH490R/p1709745541626919?thread_ts=1709739696.052919&cid=C05BFAH490R) and she said it wouldn't conflict. I'll still wait for another review though

**Review by chloerice — APPROVED** [review]
Looks great @kyledurand!! 🚀

**Comment by tjonx** [comment]
FYI, there seems to be a slight bump happening as the popover appears into place.

https://github.com/Shopify/polaris/assets/67433661/5712a3e3-8250-4d78-a334-13d569a27c57

**Pull request merged**
