### PR TITLE
Add responsive `Text` styles

### PR DESCRIPTION
**Pull request by aaronccasanova**
Closes https://github.com/Shopify/polaris-summer-editions/issues/100

https://github.com/Shopify/polaris/assets/32409546/a995b2f9-af65-44bd-b6da-7d4ce0f285a4

### CODE REVIEW

**Review by laurkim — APPROVED** [review]
💯

**Review by kyledurand — APPROVED** [review]
Code looks good 👍

**Review by sarahill — COMMENTED** [review]
@aaronccasanova  Sizes and heights look good but I just noticed the weights are off for `headingLg` -> `heading4xl`. It should be using `700` and it looks like it's using `600`. Do you want a follow-up issue for this?

**Comment by aaronccasanova** [comment]
Nice catch @sarahill! Updated https://github.com/Shopify/polaris/pull/9422/commits/a169270e9ce145ae7df2ac88f10215223af0053a

**Review by sarahill — APPROVED** [review]

**Pull request merged**
