### PR TITLE
Remove KonamiCode component

### PR DESCRIPTION
**Pull request by tmlayton**

### CODE REVIEW

**Comment by kyledurand** [comment]
This would technically be a breaking change 🤷. Can you create a v11-major branch and point to it?

**Comment by tmlayton** [comment]
Technically yes, but since it is unlisted (assumed private) I think it’s okay to not wait until a major version. It doesn’t appear to be used by any Shopify project and would be willing to bet not by any 3rd party consumer. https://github.com/search?q=org%3AShopify+KonamiCode&type=code

**Comment by tmlayton** [comment]
Although my eagerness to merge admittedly is more because I want to test the new update-performance-dispatch workflow.

**Review by alex-page — APPROVED** [review]
❤️

**Comment by tmlayton** [comment]
Updated to point to the `v11-major` branch

**Comment by isaacbowen** [comment]
👋 I'm a 3rd-party consumer using this component! \*sad trombone noises*

**Comment by chloerice** [comment]
@isaacbowen Feel free to copy the source code into your project so you don't have to remove your instance when you [upgrade to v11](https://github.com/Shopify/polaris/blob/main/documentation/guides/migrating-from-v10-to-v11.md#removed-konamicode)!

**Pull request merged**
