### PR TITLE
Update `DatePicker`

### PR DESCRIPTION
**Pull request by lgriffee**
### WHY are these changes introduced?

Resolves https://github.com/Shopify/polaris-summer-editions/issues/209

### WHAT is this pull request doing?

- Updates month title font-size, line-height, and font-weight
- Corrects arrow icon color (from introduction of primary plain button)
- Updates day cell border-radiuses 

### How to 🎩

Review on [Storybook](https://5d559397bae39100201eedc1-dfciqdralo.chromatic.com/?path=/story/all-components-datepicker--all&globals=polarisSummerEditions2023:true)
- Ensure beta flagged DatePicker styles render as expected
- Ensure no regressions to the existing DatePicker styles

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)

### CODE REVIEW

**Review by sophschneider — APPROVED** [review]
🙌✨

**Comment by sarahill** [comment]
@lgriffee  Everything visually looks good but wondering if we could update tokens? We're starting to rethink the interactive tokens since everything has a level of interactivity with the other tokens.

| new | old |
|---|---|
| `bg-primary` | `bg-interactive` |
| `bg-primary-hover` | `bg-interactive-hover` |
| `bg-primary-subdued-selected` | `bg-interactive-selected` |

**Comment by lgriffee** [comment]
@sarahill I've updated the tokens in f90d1e9 to match the new ones you've outlined!

**Review by sarahill — APPROVED** [review]

**Review by aaronccasanova — APPROVED** [review]

**Comment by aaronccasanova** [comment]
Noticed an issue right as I was closing the tab. Looks like disabled date ranges now apply a hover color:

https://github.com/Shopify/polaris/assets/32409546/a3e9cee1-0194-4543-b22b-7f650bb51ad7

**Comment by lgriffee** [comment]
Super good catch! Thanks @aaronccasanova! Looks like an unintentional specificity override. I've added an additional se23 class to override it in 3e36389

**Pull request merged**
