### PR TITLE
[AppProvider] Add click tracker to help with focus management 

### PR DESCRIPTION
**Pull request by dleroux**
### WHY are these changes introduced?

For accessibility and better UX, when Modals are closed, the focus should return back to the activator. By doing this, keyboard users don't get disoriented or aren't forced to tab back from the top of the page.

The Modal does have an activator prop to help with this issue. However,  in some instances, like Popover actions, Card actions, Page actions, we don't have the ability to supply the ref to the modal.

### WHAT is this pull request doing?

This PR is an exploration in adding context to the provider that would keep track of items being clicked. When modal or popover opens, the tracking is paused, allowing the tracker to set focus to the last clicked element when the modal is closed.

This PR is not complete. in top hatting, I noticed rolled up actions in the page header didn't receive focus, but just wanted to get feedback on the approach before continuing the explorations.

focus

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React, {useCallback, useState} from 'react';

import {Page, Button, Modal, TextContainer, Card, Stack} from '../src';

export function Playground() {
  const [active, setActive] = useState(true);

  const handleChange = useCallback(() => setActive(!active), [active]);

  return (
    <Page
      title="Playground"
      actionGroups={[
        {
          title: 'Promote',
          actions: [
            {
              content: 'Share on Facebook',
              onAction: handleChange,
            },
          ],
        },
      ]}
    >
      <Stack vertical>
        <Card
          sectioned
          title="Variants"
          actions={[{content: 'Add variant', onAction: handleChange}]}
          secondaryFooterActions={[
            {content: 'Edit shipment', onAction: handleChange},
          ]}
          primaryFooterAction={{
            content: 'Add tracking number',
            onAction: handleChange,
          }}
        >
          <p>
            Add variants if this product comes in multiple versions, like
            different sizes or colors.
          </p>
        </Card>
        <Button onClick={handleChange}>Open</Button>
      </Stack>
      <Modal open={active} title="Modal" onClose={handleChange}>
        {Array.from({length: 5}, (_, index) => (
          <Modal.Section key={index}>
            <TextContainer>
              <p>Item #{index}</p>
            </TextContainer>
          </Modal.Section>
        ))}
      </Modal>
    </Page>
  );
}

```

</details>

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

### CODE REVIEW

**Comment by dleroux** [comment]
Maybe FocusTacker is a better name.

**Comment by ry5n** [comment]
This is great, @dleroux! I can’t comment on the approach, but this would help a bunch of teams, Merchandising included @ericdesj are there front-end folks on our team who could provide feedback on this for Dan so he can decide which way to go with this?

**Comment by dleroux** [comment]
Thanks, @ry5n I did this as a proof concept because I find all the activator props are getting a little unwieldy. This would solve that and help with the scenarios where the activator is not accessible. To get moving, we would need to write tests and make sure it's actually doing what it's supposed to. 

I just haven't had the time to come back to it, hoping to at some point, but would be more than happy if someone would want to take this and run with it as well.

**Comment by ry5n** [comment]
@lsit I wonder if you could take a look at Dan’s work here so far? Maybe you could help write some tests—what do you think?

**Comment by lsit** [comment]
Hey @ry5n, I'm going on vacation after today so I won't have time to take too deep a look until the new year. But happy to take a look then if no one else has.

**Comment by jaxee** [comment]
Wow! This is amazing @dleroux 🎉
I think it'd be useful to add this to the [Sheet component](https://github.com/Shopify/polaris-react/tree/master/src/components/Sheet) as well. @ananyaneogi and I are starting to explore the modal focus issue, let us know if there's anything we can do to help you

**Comment by dleroux** [comment]
@jaxee I'm currently focused on my project. Would love it if someone could take this up as it will help with the a11y push going on at the moment. I just won't have time to get back to this for while still.

**Pull request closed without merging**
