### PR TITLE
[Typography foundations] Add responsive styling for heading2xl-4xl variants on <Text>

### LINKED ISSUE #6699: [Typography foundations] Support responsive styling for display variants on `<Text>`

### PR DESCRIPTION
**Pull request by chazdean**
### WHY are these changes introduced?

Fixes #6699 

### WHAT is this pull request doing?

Following our [type guidelines](https://www.figma.com/file/lywHPxKoSsqzhQyasj6VON/Typography-foundations?node-id=1777%3A60632) this PR adds responsive styling to our heading2xl-4xl variants using our new breakpoints

10-37-xzhir-mgw64

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';

import {Page, Text} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      <Text as="h1" variant="heading4xl">
        Heading4xl
      </Text>
      <Text as="h1" variant="heading3xl">
        Heading3xl
      </Text>
      <Text as="h1" variant="heading2xl">
        Heading2xl
      </Text>
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by alex-page — APPROVED** [review]
I don't know if the values are right... but the code looks great. Awesome work @chazdean

**Comment by alex-page** [comment]
I would love documentation for responsive type styles. Users should know what breakpoint they trigger at and why we do responsive text changes for display and not other variants. (out of scope for this PR).

**Review by laurkim — APPROVED** [review]
Nice! 🚀 💯 
Checked the [Figma](https://www.figma.com/file/lywHPxKoSsqzhQyasj6VON/Typography-foundations?node-id=1777%3A60632) and styling for breakpoint matches 👍

**Review by sarahill — APPROVED** [review]
👏

**Comment by aveline** [comment]
I wonder if it makes more sense to go with `$p-breakpoints-md-up`? Previously we used a mobile first approach but I guess we don't have a set convention for now? Might be good to have one though for consistency.

[Primer has nice breakpoint docs](https://primer.style/css/support/breakpoints#breakpoint-and-up-) and I think it would be good to stick with the convention of using `min-width` by default.

**Comment by aaronccasanova** [comment]
Echoing @aveline's comment, please update to use (mobile first) `$p-breakpoints-md-up`.

**Review by aveline — CHANGES_REQUESTED** [review]
Our breakpoint docs are still a wip but the intent is to go with a mobile first approach

https://github.com/Shopify/polaris/blob/f0ff95c6f851d554ff1a51ce36047624bd4bd9d9/documentation/guides/breakpoints-migration.md#new-breakpoints

There's also some additional background in this PR https://github.com/Shopify/polaris/pull/6106

So I would suggest going with `$p-breakpoints-md-up` and swapping the `font-size` and `line-height` values accordingly.

**Review by aveline — APPROVED** [review]
🎉

**Pull request merged**
