### PR TITLE
Update `ChoiceList` mobile styles

### PR DESCRIPTION
**Pull request by lgriffee**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-internal/issues/1590
Fixes https://github.com/Shopify/mobile/issues/33785

> [!CAUTION] 
> Basing this PR off of https://github.com/Shopify/polaris/pull/11837 and will not merge until that ships. No need to include changes from https://github.com/Shopify/polaris/pull/11878 since the helper/error text changes do not factor into clickable area. 

### WHAT is this pull request doing?

- Increases `Choice` padding so the tap target on mobile is 48px
- Improves `ChoiceList` mobile padding

| Before | After | 
| -- | -- | 
Screenshot 2024-05-06 at 3 26 43 PM|Screenshot 2024-05-06 at 3 26 38 PM|
Screenshot 2024-05-06 at 3 28 03 PM|Screenshot 2024-05-06 at 3 28 10 PM|

### How to 🎩

> [!TIP] 
> Make sure you have the breakpoint in storybook at `sm` or `xs` to see the changes!

- 📕 [Storybook Before](https://5d559397bae39100201eedc1-dopnorbvqa.chromatic.com/?path=/story/all-components-choicelist--with-children-content&globals=viewport:1)
- 📕 [Storybook After](https://5d559397bae39100201eedc1-wksqjkgeob.chromatic.com/?path=/story/all-components-choicelist--with-children-content&globals=viewport:1)

### CODE REVIEW

**Review by aveline — APPROVED** [review]
Looks good overall! Just one question about the indentation of the `children` content, I noticed it's updated to now be in line with the radio button, is that intentional? I didn't see an example [in the Figma](https://www.figma.com/file/PQUFqE9VrOtVPZbaifdL5J/Forms?type=design&node-id=2241%3A9875&mode=design&t=J8Iufa8GFxphWg1A-1).

**Comment by lgriffee** [comment]
> Looks good overall! Just one question about the indentation of the children content, I noticed it's updated to now be in line with the radio button, is that intentional? I didn't see an example in the Figma.

@aveline Yes, it was an intentional change based on [these mockups in Figma](https://www.figma.com/file/PQUFqE9VrOtVPZbaifdL5J/Forms?type=design&node-id=447-14206&mode=design&t=mk2got5K6Du99v27-4). Would be good to confirm with @heyjoethomas this is still the desired design update!

**Comment by lgriffee** [comment]
Closing in favor of [this PR](https://github.com/Shopify/polaris-internal/pull/52)

**Comment by lgriffee** [comment]
Closing in favor of build phase PR

**Pull request closed without merging**
