### PR TITLE
[Combobox] Escape special RegExp characters in Combobox example code

### PR DESCRIPTION
**Pull request by kdaviduik**
### WHY are these changes introduced?

While following this example code, our team had some errors reported because user input containing special RegExp characters was not escaped before creating the RegExp.

### WHAT is this pull request doing?

Escapes special RegExp characters in a combobox example, so that individuals following the example will not encounter errors.

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [ ] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Comment by sam-b-rose** [comment]
Hi @kdaviduik! Just to clarify, this additional code is escaping special characters when a user inputs a regular expression into the combobox?

The combobox isn't specifically designed to handle RegExp as user input. I think that would be up to the developer to determine the appropriate regex filter for their scenario. Please clarify if I misunderstood your intent.

**Comment by kdaviduik** [comment]
Hi @sam-b-rose! Not quite, the issue is that for the standard case where a user enters regular text/characters as input, and as a developer we want to treat the user's input as standard text, the example code doesn't handle that properly. It treats certain characters such as `\`, `*`, `+`, `[` in the user's input as if the user is trying to create a regular expression (even though they aren't), so it throws an error in those cases.

As part of the filtering process, the example code creates a `RegExp` out of their input, and it's that step where errors are thrown. The code I suggested is basically: `for all characters in the input that have a special meaning in regular expressions, replace them with a \ followed by that character`. This fixes the issue, as now `RegExp` interprets the user's input just as text.

For a potentially more familiar example of the same concept, in JavaScript if you want to enter a `\` in text, you need to type `\\` or else it doesn't interpret it correctly. Or if you have a string between single quotes `'`, any single quotes present in the string (as part of the string's text) must be prefixed by a `\` or else you get a syntax error. 

Eg: `const myString = 'This won\'t break the string';`

**Comment by kdaviduik** [comment]
@sam-b-rose Would love to get some type of update shipped to the Polaris docs, as copying this example code seems to be responsible for ~2000 errors in BugSnag for ~1000 users (I shipped a fix yesterday to affected admin sections). I would like to address the root cause to try to minimize re-occurrence.

If you'd like, I can modify my suggestion to put it into a helper function like `escapeRegExSpecialCharacters` or something to be a bit more easily understandable.

**Review by alex-page — APPROVED** [review]

**Comment by sam-b-rose** [comment]
I see—thanks for the clarification @kdaviduik! Using the variable name `escapeRegExSpecialCharacters` also does help add clarity as well. Thank you for addressing this issue 🎉

**Review by sam-b-rose — APPROVED** [review]

**Review by aaronccasanova — APPROVED** [review]

**Comment by kdaviduik** [comment]
- Added a [commit](https://github.com/Shopify/polaris/pull/11555/commits/1084c5c2f61ce2432b53414afd3d91101c1a61ba) where I create a helper function to escape the regex characters. 
- Since my suggestion was approved, I also applied it to the rest of the combobox examples

**Comment by kdaviduik** [comment]
Also to ship this do I just hit "Squash and merge"? Any special instructions?

**Comment by alex-page** [comment]
@kdaviduik yep just squash and merge. Thank you!

**Review by chloerice — APPROVED** [review]

**Pull request merged**
