### PR TITLE
Remove serve dependency and dev start command

### LINKED ISSUE #4322: Move serve back to devDependencies
## Issue summary

This commit moved package `serve` from `devDependencies` to `dependencies`:

https://github.com/Shopify/polaris-react/commit/d2611d6e256a73c8bb34f269190ee3bb917a0847

Please move it back! I'm guessing it was by accident. The upgrade to Polaris 6.6.0 grew my lockfile by 200 lines.

### PR DESCRIPTION
**Pull request by aaronadamsCA**
### WHY are these changes introduced?

Resolves #4322.

### WHAT is this pull request doing?

There's no reason to keep shipping an entire web server inside Polaris!

### CODE REVIEW

**Comment by ghost** [comment]
👋 Thanks for opening your first pull request. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by BPScott** [comment]
Yo @alex-page now that we're deploying storybook to chromatic rather than some custom place, can we remove the dependency on server entirely?

**Review by BPScott — APPROVED** [review]
🔥 Love me a good tidy up

**Comment by alex-page** [comment]
Thanks @aaronadamsCA 💯

**Review by alex-page — APPROVED** [review]

**Comment by ghost** [comment]
🎉 Thanks for your contribution to Polaris React!

**Pull request merged**
