### PR TITLE
Resize icons to 16x16 from 20x20 and remove surrounding padding

### PR DESCRIPTION
**Pull request by sam-b-rose**
Reduces the viewBox of SVG in `@shopify/polaris-icons` from 20x20 to 16x16. Removing the surrounding whitespace of the icon illustrations will improve predicability of the artwork size when resizing for mobile screens.

> [!CAUTION]
> This is a **breaking change** for the icons package.

🌀 [Spin URL](https://admin.web.icons-16.sam-rose.us.spin.dev/store/shop1)

### CODE REVIEW

**Comment by davebcn87** [comment]
There are some icons missing in this change, this are still in the `svg` output folder and have the 20x20 viewBox in them.
The SkeletonIcon, also has rem values, that make the code generation fail on iOS.

```
OrderFulfilledIcon.svg
BillIcon.svg
IncentiveIcon.svg
SkeletonIcon.svg
OutdentIcon.svg
DatabaseConnectIcon.svg
ListBulletedFilledIcon.svg
ViewportShortIcon.svg
BillFilledIcon.svg
```

**Comment by sam-b-rose** [comment]
Looks like this PR is conflicting with the updated icon consistency changes #11609. This is fine for _testing_ the 16x16 viewBox in Mobile. However, we'll need to redo this PR with the updated icons to make sure we don't revert any of the icons.

cc @bernardojoaogarcia

**Comment by alex-page** [comment]
@sam-b-rose I took a copy of the icons at this point in time for admin-ui-icons package. Let me know if I need to update anything.

**Pull request closed without merging**
