### PR TITLE
[IconsPage] Use fileName for code examples

### PR DESCRIPTION
**Pull request by gil--**
### WHY are these changes introduced?

Fixes broken code examples that reference name instead of fileName. See https://polaris.shopify.com/icons?icon=BillingStatementPoundMajor

CleanShot 2022-06-24 at 10 26 13

### WHAT is this pull request doing?

FileName removes spaces and correctly references what an end-user would enter
### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by alex-page — APPROVED** [review]

**Comment by alex-page** [comment]
@gil-- thank you 🙌

**Comment by alex-page** [comment]
@gil-- this is live now. If you have any feedback or thoughts on the site feel free to share them.

**Comment by gil--** [comment]
@alex-page Yea noticed it went live yesterday! Congrats to you and the team - I know it must have been a big effort! Overall, love the new site - haven't had a chance to really dig in yet but I've been using the dark mode 🤓. Also the new tokens page is great!

## My only feedback so far is:
- I miss the old props list. I used to use the Polaris site heavily to lookup prop fields & options sort of like you would do with Storybook. Looks like that was all removed?
- The [Grid Component](https://polaris.shopify.com/components/grid) in the preview is squished but CodeSandbox looks fine. Haven't really looked into it:

CleanShot 2022-06-24 at 11 29 44

CleanShot 2022-06-24 at 11 29 30

- The [Sheet component](https://polaris.shopify.com/components/sheet) is missing a deprecated warning. You obviously see the warning in dev tools but I think it'd be helpful to newcomers to show the warning on the component page like before?

**Comment by alex-page** [comment]
Thanks @gil--!!! Love that you are enjoying dark mode, it definitely helps me when late night coding. 

Yes. The props table missing has been the number one feedback from the launch. We are tracking adding it back here https://github.com/Shopify/polaris/issues/6371.

I added an issue for the Grid example here https://github.com/Shopify/polaris/issues/6390. Thanks for noticing that!

I added an issue for the deprecation warning banners missing. https://github.com/Shopify/polaris/issues/6391

Thank you @gil-- always appreciate your attention to detail. Hope you have a great weekend 🚀

**Pull request merged**
