### PR TITLE
Getting Started update

### PR DESCRIPTION
**Pull request by tracytees**
This PR updates the getting started section based on internal feedback:
- Removes `/design`, `/develop`, `/shared-resources`, and `/patterns-components-and-tokens` pages
- Copy edits on `/getting-started` and `/polaris-101` 

|Getting started|Polaris-101|
|---|---|
|localhost_3000_getting-started|localhost_3000_getting-started (1)|

### CODE REVIEW

**Review by alex-page — APPROVED** [review]

**Comment by jared-fanning** [comment]
I'm curious about the re-ordering of the Polaris 101 sections? Initially the approach was to start with Polaris -> the Admin (and apps). Everything else looks good on my end, thanks!

**Comment by chloerice** [comment]
> I'm curious about the re-ordering of the Polaris 101 sections? Initially the approach was to start with Polaris -> the Admin (and apps). Everything else looks good on my end, thanks!

Great question! The thinking there was that the intro sentence closes with, "the Shopify admin." So it felt more natural and less redundant to start with "What's the Shopify admin" before jumping in to the Polaris-centric sections.

**Comment by jared-fanning** [comment]
> 
> Great question! The thinking there was that the intro sentence closes with, "the Shopify admin." So it felt more natural and less redundant to start with "What's the Shopify admin" before jumping in to the Polaris-centric sections.

I'm ok with that! One other smaller thing — could we find a more active screen example for the mobile app image? (vs onboarding 0 orders/sales)? Maybe reaching out to the Core Mobile UX folks?

**Comment by tracytees** [comment]
Let's make some adjustments based off of Jared's feedback. I've DM-ed @chloerice the adjustments needed :)

**Comment by SeanyB** [comment]
Is the Sandbox (Alpha) link meant to be added under Getting Started?

At the moment, I see it on our site as a top-level item, and under Contributing. I think we should have it only in one location.

**Comment by chloerice** [comment]
@SeanyB These screenshots were taken before the Sandbox was moved to top level in a different PR. What you see in prod is correct, the Sandbox's location is in the top-level of the nav 💯

**Pull request merged**
