### PR TITLE
Update Modal

### PR DESCRIPTION
**Pull request by laurkim**
### WHY are these changes introduced?

Fixes [#571](https://github.com/Shopify/polaris-summer-editions/issues/571).
Fixes [#589](https://github.com/Shopify/polaris-summer-editions/issues/589).
Fixes [#93692](https://github.com/Shopify/web/issues/93692).

### WHAT is this pull request doing?

Adds `bg-secondary` experimental token.
Fixes Modal Header background color.
Fixes Modal CloseButton background color for interactive states.
Fixes Modal CloseButton border radius on focus-ring when focused.

### How to 🎩

🚨 **For tophatting, please focus on close button interactive states (hover, focus, active, pressed).**

[Modal with title story](https://5d559397bae39100201eedc1-zluizpzulw.chromatic.com/?path=/story/all-components-modal--default&globals=polarisSummerEditions2023:true)
[Modal without a title story](https://5d559397bae39100201eedc1-zluizpzulw.chromatic.com/?path=/story/all-components-modal--without-a-title&globals=polarisSummerEditions2023:true)

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by kyledurand — APPROVED** [review]
This looks good! Do we need an active bg color for the modal close button? We typically go a touch darker on the active state

**Comment by laurkim** [comment]
> This looks good! Do we need an active bg color for the modal close button? We typically go a touch darker on the active state

@kyledurand oh good call out, just pushed up a commit to use `bg-transparent-active-experimental` on active/pressed states 👍

**Comment by bernardojoaogarcia** [comment]
@kyledurand Yup, should be reflecting the Plain Primary button's active state 👍. Looks great Lo!

**Review by bernardojoaogarcia — APPROVED** [review]

**Review by sophschneider — APPROVED** [review]
💗

**Pull request merged**
