### PR TITLE
[Migrator] Add migrate-motion migration for transition easing function

### PR DESCRIPTION
**Pull request by jesstelford**
*NOTE*: Includes changes in #7403, so that PR should be merged first. In the mean-time, you can [view the changes for this PR only](https://github.com/Shopify/polaris/compare/migrate-motion...migrate-motion-easing).

### WHY are these changes introduced?

ref https://github.com/Shopify/polaris/issues/7213

This PR covers the `transition` and `transition-timing-function` properties, their various complex uses and a couple of edge cases as seen in the wild.

### WHAT is this pull request doing?

Example migrations (taken from the test files):

* `transition-timing-function: linear`
    ↳ `transition-timing-function: var(--p-linear)`
* `transition-timing-function: legacy-polaris-v8.easing('in')`
    ↳ `transition-timing-function: var(--p-ease-in);`
* `transition: opacity 300ms legacy-polaris-v8.easing('base');`
    ↳ `transition: opacity var(--p-duration-300) var(--p-ease);`

Will output various error messages for things it can't migrate:

* `transition-timing-function: legacy-polaris-v8.easing(anticipate);`
    ↳
    ```
    /* polaris-migrator: Unable to migrate the following expression. Please upgrade manually. The anticipate easing function is no longer available in Polaris. See https://polaris.shopify.com/tokens/motion for possible values. */
    transition-timing-function: legacy-polaris-v8.easing('anticipate');
    ```
* `transition-timing-function: cubic-bezier(0, 0, 1, 1);`
    ↳
    ```
    /* polaris-migrator: Unable to migrate the following expression. Please upgrade manually. Unexpected easing function 'cubic-bezier'. See https://polaris.shopify.com/tokens/motion for possible values. */
    transition-timing-function: cubic-bezier(0, 0, 1, 1);
    ```

---

**Open Question**: Do we consider `cubic-bezier()` / `linear()` / other built-in CSS easing functions as failures? I assume so (and have coded it to insert a comment when they're detected), but want to be sure before this gets merged.

### CODE REVIEW

**Review by sam-b-rose — APPROVED** [review]
This is looking 🔥 💯  love the use of the property keys in the plugin Declaration object. Is this ready to run on web or are there still edge-cases that need to be handled?

Also, can you add a small bit of documentation for this migration in the migrator package `README.md`?

**Comment by jesstelford** [comment]
These additions have been combined into #7403

**Pull request closed without merging**
