### PR TITLE
[Inputs] Update border widths

### LINKED ISSUE #9595: [DropZone] .hasOutline:not(.focused) selector overrides .isDisabled styles unexpectedly.
> https://github.com/Shopify/polaris/blob/bc12dfa1845fff0bd46a8a3cb802d3b4f8c93ac3/polaris-react/src/components/DropZone/DropZone.scss#L77-L107

> The `:not(.focused)` selector will match even when `.isDisabled` exists, and so the border color is being set to the focus color: Screenshot 2023-07-03 at 12 12 17 pm

See @jesstelford's [comment](https://github.com/Shopify/polaris/pull/9586#issuecomment-1617123203) in #9586 

## Expected behavior

Disabled DropZones should have a border-color of `p-color-border-disabled` and take precedence over styles specified in `.hasOutline:not(.focused)` 

## Actual behavior

`.hasOutline:not(.focused)` styles currently override the border-color of disabled DropZones. 

## Steps to reproduce the problem

* See this [storybook example](https://5d559397bae39100201eedc1-pisfvcgvfq.chromatic.com/?path=/story/all-components-dropzone--disabled) 
* inspect the :after element  in the div with the `.DropZone-hasOutline` class.

### PR DESCRIPTION
**Pull request by sophschneider**
### WHY are these changes introduced?

Resolves [this issue](https://github.com/Shopify/polaris-summer-editions/issues/691)
Resolves [this issue](https://github.com/Shopify/polaris/issues/9595)

### WHAT is this pull request doing?

Edit: See [comment below](https://github.com/Shopify/polaris/pull/9586#pullrequestreview-1513216889) for updated values, this table is now outdated

> Its worth noting `0.66px` border width rounds to `0.5px` in all browsers on my machine with default display settings

Exact values from Figma:

|Component ________|Default|Hover|Active|Focus|Disabled|Error|
|-|-|-|-|-|-|-|
|Select|`0.66px` border-input|`0.66px` border-input-hover|shadow-inset-md|`0.66px` border-input|`0.66px` border-disabled|`1px` border-critical-strong|
|TextField|`0.66px` border-input|`0.66px` border-input-hover|`1px` border-input-active|(`0.66px` border-input|`0.66px` border-disabled|`1px` border-critical-strong|
|RadioButton|`0.66px` border-input|`1px` border-input-hover| n/a |(filled when focused)|`1px` border-disabled| n/a |
|Checkbox|`0.66px` border-input|`1px` border-input-hover| n/a |`0.66px` border-input|`1px` border-disabled|`1px` border-critical-strong|
|Dropzone|`0.66px` border-input|`0.66px` border-input-hover|`0.66px` border-input-active| n/a |`0.66px` border-disabled|`0.66px` border-critical-strong|

### How to 🎩

Storybook link in CI for components above with feature flag on
[See this in the admin](https://admin.web.input-borders.sophie-schneider.us.spin.dev/store/shop1)

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)

### CODE REVIEW

**Comment by jesstelford** [comment]
Tested using [this Storybook](https://5d559397bae39100201eedc1-pisfvcgvfq.chromatic.com/?path=/story/all-components-dropzone--default&globals=polarisSummerEditions2023:true) built from commit `bc12dfa1845fff0bd46a8a3cb802d3b4f8c93ac3`

---

Select--Focus is `--p-color-border-input-active-experimental` not `border-input`: 
Screenshot 2023-07-03 at 11 36 37 am

Which seems correct based on the code, but doesn't match [Figma](https://www.figma.com/file/jLLkmo9r28hiqPvf4s90E4/Polaris-Uplift-Components-%5Bgen3%E2%80%93alpha%5D?type=design&node-id=405-2009&mode=design&t=mNDoKgI0v2BHuUw4-4). If we go with what's in the code, then we'd also need to update Checkbox--focus.

---

RadioButton--Disabled is `--p-border-width-1-experimental` not `1px`: Screenshot 2023-07-03 at 11 47 44 am

Which should be ok - it's the same color as the disabled bg color, so it'd never be noticed. However, Figma has _no_ border, and if the disabled bg vs diabled border color definitions drift, it cause a visual regression. I'm wondering if the border should simply be `transparent` to remove the border and just display the background color as per Figma?

---

The DropZone--disabled styles are getting the "Focus" styles applied to them. This is happening because the use of `:not` selectors:

https://github.com/Shopify/polaris/blob/bc12dfa1845fff0bd46a8a3cb802d3b4f8c93ac3/polaris-react/src/components/DropZone/DropZone.scss#L77-L107

The `:not(.focused)` selector will match even when `.isDisabled` exists, and so the border color is being set to the focus color: 
Screenshot 2023-07-03 at 12 12 17 pm

---

Everything else looks good 👍

**Comment by gwyneplaine** [comment]
> RadioButton--Disabled is `--p-border-width-1-experimental` not `1px`: Screenshot 2023-07-03 at 11 47 44 am
> 
> Which should be ok - it's the same color as the disabled bg color, so it'd never be noticed. However, Figma has _no_ border, and if the disabled bg vs diabled border color definitions drift, it cause a visual regression. I'm wondering if the border should simply be `transparent` to remove the border and just display the background color as per Figma?

The Figma file also has a 1px border 
Screenshot 2023-07-04 at 10 36 35 am

That said i agree about the risk of drift, if the intention is for it to be one colour, then adding a border that's a different token might be superfluous, likely something we can address in a separate PR.

**Review by gwyneplaine — APPROVED** [review]
Radio, Checkbox and Dropzone changes lgtm
The issue that @jesstelford  mentioned circa :not(.focused) in DropZone is a pre-uplift bug, and can be resolved separate to this PR (imo)

**Comment by gwyneplaine** [comment]
Logged an issue for the DropZone issue [here](https://github.com/Shopify/polaris/issues/9595)
If you decide to good samaritan that change into this PR.

**Comment by sophschneider** [comment]
@jesstelford +1 what Charles said, the disabled border is in figma! I have a table in the PR description with all the values from figma. I honestly think its good that they are separated and we are not using `transparent` or the same value, because one day if we want to up the contrast of disabled input borders we can do that, but for now they are the same. So I think the separation as it is makes sense.

Fixed the dropzone disabled border issue with a specificity bump, thanks for catching it and making the issue!

**Review by sarahill — COMMENTED** [review]
1. Borders
All borders should be `.66px` by default and `1px` for active states across inputs (`Select` is the exception)

2. Background + border colors for all inputs 
(note: looking at disabled states but we'll handle any updates to those separately so we can look at them as a whole)

| default | hover | focus | active |
|---|---|---|---|
| `bg-input` | `bg-input-hover` | `bg-input-hover` | `bg-input-active` |
| `border-input` | `border-input-hover` | `border-input-hover` | `border-input-active` |

[Figma](https://www.figma.com/file/jLLkmo9r28hiqPvf4s90E4/Polaris-Uplift-Components-%5Bgen3%E2%80%93alpha%5D?type=design&node-id=92656-55441&mode=design&t=tHDUP5rcTL7tcTma-4)
image

**Comment by sophschneider** [comment]
@sarahill thanks for the design updates, this makes a lot more sense!! My `Storybook publish` link in the CI should have the updated border-widths and backgrounds, lmk if I missed anything :)

**Review by sarahill — COMMENTED** [review]
This looking good! 

Caught one thing: After seeing this in Storybook I realized I messed up on the `focus` state for `TextField` and `Select`. 

For both of those active will be:

- `bg-input-active`
- `border-input-active`
- `1px` border

`TextField` will have the same styles for `active` and `focus`.

image

The intent is to have them look like this from the prototype (we added back the focus ring back though which isn't reflected here):

**Review by sarahill — APPROVED** [review]
👏

**Pull request merged**
