### PR TITLE
(polaris-icons) Add Dynamic Source icons

### PR DESCRIPTION
**Pull request by gil--**
### WHY are these changes introduced?

Adds Shopify admin dynamic source icons to Polaris. Examples within the Theme Editor:

### Connect dynamic source
CleanShot 2022-08-26 at 17 22 59

### Insert dynamic source
CleanShot 2022-08-26 at 17 26 57

I'd like to use these for a similar use-case of connecting to metafields within my app and would like to be consistent with Shopify's icons. Can we consider pulling these two icons into Polaris?

### WHAT is this pull request doing?

Adds Shopify admin dynamic source icons to Polaris.

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page, Icon} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      <Icon source={DynamicSourceMajor} />
    </Page>
  );
}
```

</details>

### CODE REVIEW

**Comment by alex-page** [comment]
@gil-- I want to connect the designers who built this originally. Do you know what part of the admin this is used in?

**Comment by gil--** [comment]
@alex-page 

Shopify's theme editor sidebar

CleanShot 2022-08-26 at 17 33 34

**Comment by alex-page** [comment]
Thanks @gil-- I am connecting with some of the designers on the theme editor for context. I also deleted my comment as I saw you mentioned that and I just didn't read carefully enough (they will likely see my message Monday). Cheers!

**Comment by Rusty-UX** [comment]
@gil-- & @alex-page Thanks for the heads up I'll get these added next week - we have 4 icons we use in the editor we want to bring in here. @gil-- Curious how you want to use these?

1. Major datasource
2. Minor datasource
3. Major datasource add
4. Minor datasource add

**Comment by alex-page** [comment]
Nice @Rusty-UX. Next week could you take a look at this PR's svg's (I assume they are just copy pasted from the admin and good to go) and let me know if there are any issues. We also should add yourself or anyone else that authored the icon to the author section.

Gil already has these icons in the pull request:
- [x] DynamicSourceMajor.svg
- [ ] DynamicSourceMinor.svg
- [ ] InsertDynamicSourceMajor.svg
- [x] InsertDynamicSourceMinor.svg



@gil-- hopefully we can ship this early next week.

**Comment by gil--** [comment]
@Rusty-UX I let customers enter static text or select data from a list of metafield definitions.

**Customer selects metafield definition:**
CleanShot 2022-08-26 at 22 26 27@2x
CleanShot 2022-08-26 at 22 26 36@2x
CleanShot 2022-08-26 at 22 26 42@2x
CleanShot 2022-08-26 at 22 26 09@2x

**Comment by Rusty-UX** [comment]
Thanks @gil-- Will follow up later this week with an update

**Pull request closed without merging**
