### PR TITLE
[Icon] Update Tablet icon design

### PR DESCRIPTION
**Pull request by trtri2**
### WHY are these changes introduced?

part of https://github.com/Shopify/retail-hq-store-management/issues/558

exported the icon SVG from this [figma](https://www.figma.com/design/fVIazfJNe3AOJTJmBKgTO9/Polaris-Gen-3-Icons?node-id=22456-381&t=z3AchS95yJQadj85-0) 

- Update the tablet icon to the new design (it was previously too similar to the mobile icon to distinguish the two)

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [ ] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Comment by alex-page** [comment]
@trtri2 what is the timeline and need for this adjustment? Can this wait? We are rebuilding the icon library right now.

**Comment by trtri2** [comment]
> @trtri2 what is the timeline and need for this adjustment? Can this wait? We are rebuilding the icon library right now.

Hey @alex-page.

We received some UX feedback on one of our POS app UI editors, where you can change device preview to mobile or tablet. 
Currently, the two icons are nearly indistinguishable. Ideally we'd like to have this improvement in sooner rather than later, but it's non-critical so shouldn't be a blocker for it.

image

If we were to wait for this rebuild, do you have a timeline/estimate on that which I can communicate to my team and let them know?

**Comment by alex-page** [comment]
@trtri2 please review the 16x16 viewbox in this PR https://github.com/Shopify/admin-ui-foundations/pull/660

**Comment by trtri2** [comment]
Closing in favour for the new admin ui library

**Pull request closed without merging**
