### PR TITLE
Use a float for `fill-opacity` on two icons for better compatibility

### PR DESCRIPTION
**Pull request by lfroms**
### WHY are these changes introduced?

Using a percentage string for `fill-opacity` on SVG files is not compatible with Android native platforms, which only support floats.

### WHAT is this pull request doing?

This PR updates `SortAscendingMajor` and `SortDescendingMajor` to use `0.5` instead of `50%` for `fill-opacity`.  There are no visual changes.

### CODE REVIEW

**Review by alex-page — APPROVED** [review]
Gosh. Thank you for finding this. Can we add configuration to `svgo` to stop this from happening again?

https://github.com/Shopify/polaris/blob/0a525643d9458208c08d0921f9b5438425917437/polaris-icons/rollup.config.mjs#L104-L145

**Comment by lfroms** [comment]
> Gosh. Thank you for finding this. Can we add configuration to `svgo` to stop this from happening again?

Hmm... I looked through the `svgo` docs but it doesn't seem like there are any rules or plugins that would be suitable.  I would imagine that it might be tricky to capture all the cases because this isn't the only property that supports percentages.  That being said, if you have anything in mind, I can circle back and implement it separately.

**Comment by BPScott** [comment]
https://github.com/Shopify/polaris/blob/main/polaris-icons/tests/validate-svg-content.test.js is a set of tests against icon content, ensuring things like "has the expected viewbox size", "doesn't use unexpected colors" and "doesn't use unexpected elements or properties.

You could add a test in there to ensure that fill-opacity et all do not contain percentage symbols

**Comment by lfroms** [comment]
> https://github.com/Shopify/polaris/blob/main/polaris-icons/tests/validate-svg-content.test.js is a set of tests against icon content, ensuring things like "has the expected viewbox size", "doesn't use unexpected colors" and "doesn't use unexpected elements or properties.
> 
> You could add a test in there to ensure that fill-opacity et all do not contain percentage symbols

Nice!  I'll take a look. 👍

**Pull request merged**
