### PR TITLE
Update `ShadowBevel` component and mixin

### PR DESCRIPTION
**Pull request by aaronccasanova**
Closes https://github.com/Shopify/polaris-summer-editions/issues/888

- Added square `shadow-bevel` to `LegacyCard` at `breakpoints-xs`
- Fixed invalid property value `border-radius: none`

  image

- ~Set the default `shadow-bevel` `$zIndex` to `200`~ (UPDATE: The default `$zIndex: 200` shadow-bevel was reverted to avoid unintended overlapping. Instead, we adjusted `z-index` stack levels on a case by case bases so overrides are explicit and not hiding the fact the current implementation has edge cases)

  This reveals a majority of the missing `shadow-bevel`s in [issue #888](https://github.com/Shopify/polaris-summer-editions/issues/888) by positioning the pseudo-element 100 stack levels above our `--p-z-index-1` token.

<details>
  <summary><code>LegacyCard</code> before/after screenshots</summary>

Before:

image

After:

 doimage

</details>

<details>
  <summary><code>Popover</code> before/after screenshots</summary>

Before:

image

After:

image

</details>

<details>
  <summary><code>MediaCard</code> before/after screenshots</summary>

Before:

image

After:

image

</details>

**Known issue:** The `IndexTable` loading state panel sits at `z-index: 400` and we are unable to increase the `shadow-bevel` above that without overlapping other components. See below

<details>
    <summary><code>IndexTable</code> before/after screenshots</summary>

Before:
image

> **Note: The PR will keep this behavior 👆**

After:
Screenshot 2023-07-07 at 11 55 40 AM

</details>

### CODE REVIEW

**Review by sophschneider — APPROVED** [review]

**Comment by sarahill** [comment]
### Customers index
image

### Settings > Giftcards
image
image

### Small screens
Looks like legacy card on small screens are losing a shadow but can't quite tell when inspecting. Myabe just my eyes but throwing it here to double check.
image

---
I think these are custom cards:

### Settings > Languages (I think these are custom cards)
image

### Marketing  (I think these are custom cards)
image

### Orders Index table
(Chloe mentioned this is custom and is making a follow-up PR)

**Comment by qt314** [comment]
@chloerice @sarahill @aaronccasanova I am updating all the custom cards in web (see [backlog](https://github.com/orgs/Shopify/projects/7136/views/1) in progress and ready to review). As long as this mixin is accessible from web I can update them

**Review by sam-b-rose — APPROVED** [review]

**Review by chloerice — APPROVED** [review]
Dug through the Spinstance and didn't find any new edge cases :shipit:

**Pull request merged**
