### PR TITLE
Rebuild `Layout` stories with new layout components

### LINKED ISSUE #7357: [Layout foundations] Rebuild `Layout` component with new layout primitives

### PR DESCRIPTION
**Pull request by aveline**
# Exploration ‼️ Do not merge ‼️

### WHY are these changes introduced?

Relates to #7357  

### WHAT is this pull request doing?

Our intent is to deprecate the existing `Layout` component in favour of more composable layout primitive components. This PR rebuilds the existing `Layout` storybook examples using those layout primitives to demonstrate that they can replace the existing `Layout` component.

Initially I had thought an interim step could be to update the internals of the `Layout` component to use the layout primitives, but due to the api of the `Layout` component this is not straightforward.

Further exploration needs to be done in `web` to understand the impact of switching to our breakpoint tokens. The existing `Layout` component switches to a single column view at a breakpoint of `820px` which falls between our defined `md` and `lg` breakpoints. In these examples I have used the `lg (1040px)` breakpoint to trigger the reflow.

### CODE REVIEW

**Comment by aveline** [comment]
Recreating `Layout` with our layout primitives works well, but one thing I don't feel great about is for the [primary/secondary](https://storybook.polaris.shopify.com/?path=/story/all-components-layout--two-columns-with-primary-and-secondary-widths) use case. Currently, prototyping on the Product Details Page in the Admin implementing the primary/secondary columns looks like this 

```
<Columns
  columns={{
    xs: 1,
    lg: 'minmax(480px,2fr) minmax(240px, 1fr)',
  }}
>
```

I think the minmax column widths are a design decision that should be packaged up in an easy to use component rather than left to the users to specify every time they want to implement primary/secondary columns. Maybe that's a prop in `Columns` or a new layout component? Thoughts?

admin web layout aveline-thelen us spin dev_store_shop1_products_1 (4)

**Comment by kyledurand** [comment]
I'm in favour of ditching primary / secondary and only allowing `oneThird`, `twoThirds`, and `oneHalf`, with a default to full width. [This was what I had when I replaced it with grid](https://github.com/Shopify/polaris/pull/6453/files#diff-ab5a1bacef06f611114c88bb7db25e732968bc1ac31305b0eddecc96b9f7ddf2R6-R16) (had to be reverted while I was away because it was too much work to migrate existing annotated sections to be composed).

**Comment by sarahill** [comment]
I agree with Kyle's suggestion on ditching primary / secondary and only allowing `oneThird`, `twoThirds`, and `oneHalf`, with a default to full width.

We're starting to see different arrangements and that approach feels like it will scale better. The B2B customers page feels like a good example
image

**Comment by aveline** [comment]
Primary/secondary essentially does map to `twoThirds` and `oneThird` with some additional constraints for minimum column sizes, but overall the intent is the same. I agree that `twoThirds` and `oneThird` is much more clear so am in favour of that wording.

To be clear though, we are also saying we no longer want to concern ourselves with minimum column widths? We would support `twoThirds` and `oneThird` on a small screen size. Something like

localhost_6006_iframe html_args= id=all-components-columns--columns-with-template-columns viewMode=story (1)

**Comment by aveline** [comment]
Just wanted to document a few more of my findings from exploring rebuilding `Layout` in `web` on the ProductDetails page

`Card` currently [sets some spacing when they are adjacent](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/Card/Card.scss#L8). In rebuilding with our layout components, `AlphaStack` should be used to manage spacing between elements including Cards. So this results in double spacing

admin web layout aveline-thelen us spin dev_store_shop1_products_1 (10)
`AlphaStack` outlined in blue

admin web layout aveline-thelen us spin dev_store_shop1_products_1 (9)
With the adjacent `Card` spacing removed, `AlphaStack` provides the correct spacing, but now there are spacing issues introduced in other areas.

**Comment by laurkim** [comment]
> With the adjacent Card spacing removed, AlphaStack provides the correct spacing, but now there are spacing issues introduced in other areas.

Out of curiosity, what are the other areas that are affected?

Also, I think of the two screenshots, imo the decreased spacing between the organization card and online store card looks better because it matches the spacing of cards to the left but maybe @sarahill has other opinions?

**Comment by aveline** [comment]
> what are the other areas that are affected?

On the second screenshot the spacing between **Options** and **Variants** is missing.

> the decreased spacing between the organization card and online store card looks better

Yes that's the correct spacing. The previous screenshot is showing double spacing because it's getting spacing from both `AlphaStack` and `Card` which is not what we want.

**Comment by aveline** [comment]
Just wanted to continue the exploration on what the api could look like for `Columns` to simplify the `oneThird` and `twoThirds` case.

Jamming with both @kyledurand and @aaronccasanova has led to these ideas

We could allow the columns to be set in one of three ways, a `number` which will set that number of equal width columns, a `string` which has to be valid css, or an `array` which could include either css or a string that maps to a width.

```
type ColumnWidths = 'oneThird' | 'half' | 'twoThirds';

<Columns columns={{xs: 1, md: '1fr 2fr', lg: ['1fr', 'twoThirds']}}
```

Alternatively, we could create some custom properties that map to widths which could then be passed in as valid css

```
--p-columns-oneThird: minmax(0, 1fr);
--p-columns-twoThirds: minmax(0, 2fr);

<Columns columns={{xs: 1, md: 'var(--p-columns-oneThird) var(--p-columns-twoThirds)'}}
```

This is a bit simpler to implement than the first approach, but the downside is the custom property would live in the tokens package and become separated from the `Columns` component which lives in the Polaris package.

Please share thoughts on either of these approaches.

**Comment by kyledurand** [comment]
I like the array api over the custom properties option but I think we should be more restrictive in what we allow to be passed in. 

If we allow `lg: ['1fr', 'twoThirds']` then we're going to have a harder time typing the props which means no autocomplete. It would sort of defeat the purpose of allowing both raw string and array.

I've [prototyped](https://github.com/Shopify/polaris/pull/7536/files#diff-980afd99ba8fd2e40902940a4293493ad6657205eb0cb8e741a80c3fed2b5fb7) up what I think I would do.

I did consider allowing other strings to be passed into the array but I think that encourages breaking out of our grid system and getting away from the rule of thirds which we should embrace where we can. 

I've pushed up that work [here](https://github.com/Shopify/polaris/compare/proto_columns-niceties-with-mixed-string-array?expand=1) if you want to check it out

**Comment by aveline** [comment]
Sounds good @kyledurand. I think it makes sense to go with the array api and restrict it to set widths and not allow mixing in strings of raw css. If more flexibility is needed beyond the set widths, then consumers do still have the option to go with strings for full control and customization.

**Comment by sarahill** [comment]
Just catching up on the discussions here.

It sounds like the intent is to deprecate the `Layout` component and rebuild any current layouts that use it with the smaller primitives. Is that right?

I personally like that approach and the stories are feeling good. You mentioned further exploration needs to be done in web to understand the impact of switching to our breakpoint tokens. Is there anything else we may need to look out for with this approach in terms of migration?

**Comment by aveline** [comment]
> You mentioned further exploration needs to be done in web to understand the impact of switching to our breakpoint tokens.

@kyledurand mentioned in another thread in Slack that he and @zecarlostorre had gone through this a while back and agreed that updating the switch to the `lg` breakpoint makes sense.

**Comment by aaronccasanova** [comment]
> If we allow lg: ['1fr', 'twoThirds'] then we're going to have a harder time typing the props which means no autocomplete. It would sort of defeat the purpose of allowing both raw string and array.

Wanted to mention that I don't think the types should be a blocker here if folks prefer that API.

There's a pretty elegant TypeScript syntax to allow a specific string or any string `(string & {})`:
image

**Comment by aveline** [comment]
Closing this as the exploration has run its course. Some good findings have helped inform our approach.

**Pull request closed without merging**
