### PR TITLE
[Colorpicker] Add hex/alpha text fields

### PR DESCRIPTION
**Pull request by ruairiphackett**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-ux-archive/issues/276 [archived issue].

Replacement for https://github.com/Shopify/polaris/pull/2186

There was [some interest](https://github.com/Shopify/polaris/pull/2186#issuecomment-980440872) by @alex-page in having this work revisited & I had been meaning to rework #2186 when I got a chance.

Some of the work in #2186 was already added in #4152.

This PR adds hex and transparency text fields to the `ColorPicker` to make colour picking functionality more accessible.

The specific a11y issues it tries to solve are:

>- The component requires the use of the mouse or touch, since it is implemented with mouse-only events on elements that are not natively interactive (elements).
>- The component is skipped over by screen readers, since there are no semantic elements or roles available.

#### After:

Adds a new optional prop `textEditor` to `ColorPicker`.

When `textEditor` is `true` 2 new text fields are added to the `ColorPicker` that allow the user to adjust the colour and alpha values by entering text values for each.

There are also some new examples added to the `ColorPicker` storybook.

Below is a description of allowed values for both fields:

#### Accepted values:

Text field that allows user to enter `hex` or `rgb` values for the colour. The value will be entered when focus moves from the field or the user presses the enter key. The value is then converted and displayed as a 6 digit `hex` code.

3 & 6 digit hex codes:

- #000000
- 000000
- #000
- 000

rgb colours:

- rgb(255,255,255)

<details>
<summary>Recording</summary>

Text field that allows user to enter hex or rgb values for the colour. The value will be entered when focus moves from the field or the user presses the enter key.
</details>

### `AlphaField`

Text field that allows user to enter a value between 0 and 100 for the colour's alpha value.

Pressing the up and down arrows while this field is in focus will increase and decrease the value by 1 respectively.

Holding the shift key and pressing the up and down arrows while this field is in focus will increase and decrease the value by 5 respectively.

<details>
<summary>Recording</summary>

Text field that allows user to enter a value between 0 and 100 for the colour's alpha value. Pressing the up and down arrows while this field is in focus will increase and decrease the value by 1 respectively. Holding the shift key and pressing the up and down arrows while this field is in focus will increase and decrease the value by 5 respectively.
</details>

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React, {useState} from 'react';

import {ColorPicker, Page} from '../src';

export function Playground() {
  const [color, setColor] = useState({
    hue: 300,
    brightness: 1,
    saturation: 0.7,
    alpha: 0.7,
  });

  return (
    <Page title="Playground">
      <ColorPicker onChange={setColor} color={color} allowAlpha textEditor />
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Comment by ruairiphackett** [comment]
@alex-page I recreated this from #2186 following this discussion: https://github.com/Shopify/polaris/pull/2186#issuecomment-980440872

Apologies for the delay in returning to this work. Hopefully it will still be of use, if not it was still a good learning experience returning to it.

**Comment by alex-page** [comment]
@ruairiphackett this component is challenging and might be better suited as a pattern. The missing UX that you are building is not essential for every use case of the color picker. It's definitely useful but it's a composition of parts to create a solution. Take a look at patterns, we plan to add these as component code alongside our components. https://polaris.shopify.com/patterns

If you do still want to ship this we would have to rewrite the layout using our new layout primitive components. https://polaris.shopify.com/components/layout-and-structure

**Comment by pama1999** [comment]
this needs to be merged asap :) 👍🏽 +1

**Comment by alex-page** [comment]
@pama1999 no it doesn't.

**Comment by pama1999** [comment]
> @pama1999 no it doesn't.

Okey then how about updating the docs of polaris and replacing the deprecated components with the new ones ;)

**Pull request closed without merging**
