### PR TITLE
[ChoiceList] Fix children spacing

### PR DESCRIPTION
**Pull request by kyledurand**

### CODE REVIEW

**Comment by aveline** [comment]
Prod|Spin
:----:|:----:
Screenshot 2023-01-05 at 7 42 39 AM|Screenshot 2023-01-05 at 7 39 32 AM

The top padding is still creating extra spacing 🤔

**Comment by kyledurand** [comment]
Can you link to that page @aveline? Can you tell if it's another instance of margin collapse or is it that the children aren't getting rendered in production

**Comment by kyledurand** [comment]
I found it after clicking around on the discount page. I think we'll need to not render children if they're not present in this case since it is margin collapse. Wonder if that could cause issues though

**Edit** I think the above is an implementation issue. Children shouldn't be rendered unless that option is selected. I'm creating a better example to showcase this

**Comment by aveline** [comment]
Yes, worth trying though and checking in `web`.

**Comment by aveline** [comment]
Or, a bit hacky we could make the padding conditional on `renderedChildren`

**Review by sarahill — APPROVED** [review]
✅ LGTM

Some things I think we can tighten up in a separate issue but this matches what I'm seeing in prod.

**Review by aveline — APPROVED** [review]
Looks like it renders as expected when implemented correctly and empty children aren't rendered.

**Comment by kyledurand** [comment]
> Or, a bit hacky we could make the padding conditional on renderedChildren

`renderChildren` is a function with a return value in the case of what's going on in web so there's really no way for us to check that here

**Pull request merged**
