### PR TITLE
[Tabs] Prevent Tabs’s onSelect prop from triggering a window scroll

### LINKED ISSUE #2165: Clicking Tab component can disrupt scroll position
## Issue summary

Clicking on a `<Tab />` places focus on the panel below it, which disrupts scroll position when the panel contains a lot of content.

## Expected behavior

I expect scroll position to remain the same when I click on a tab.

At least, I would hope for a prop I could pass to `<Tabs />` (`preserveScroll`?) that would disable the auto-scroll on focus.

## Actual behavior

<details>
  <summary>GIF of scroll position disruption</summary>
  Scroll position disruption
</details>

## Steps to reproduce the problem

1. Create some markup with the `<Tabs />` component where the panels below it have varying (great) height
1. Click different tabs and watch scroll position change

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.16.0
- Browser: Chrome
- Device: MacBook Pro
- Operating System: macOS 10.14.6

### PR DESCRIPTION
**Pull request by debchn**
### WHY are these changes introduced?

Fixes #2165 

Tabs focus on their contents when onSelect is triggered. When the contents of a tab are larger than the screen, this would alter scroll position in a jarring way. These changes prevent the scrolling.

### WHAT is this pull request doing?

Passes `preventScroll` to `focus`

<details>
  <summary>Before GIF</summary>
  Scroll problem
</details>

<details>
  <summary>After GIF ✨</summary>
  Constant scroll position
</details>

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React, {useState} from 'react';
import {Page, Tabs, Card} from '../src';

export function Playground() {
  const [currentTab, changeTab] = useState(0);
  const tabs = [
    {
      id: 'tab-1',
      content: 'Tab 1',
    },
    {
      id: 'tab-2',
      content: 'Tab 2',
    },
    {
      id: 'tab-3',
      content: 'Tab 3',
    },
  ];
  const height = 100 + currentTab * 1000;

  return (
    <Page title="Playground">
      <Card>
        <Tabs tabs={tabs} selected={currentTab} onSelect={changeTab}>
          <Card.Section title={tabs[currentTab].content}>
            <div style={{border: 'solid 1px black', height}} />
          </Card.Section>
        </Tabs>
      </Card>
    </Page>
  );
}


```

</details>

### 🎩 checklist

* [x] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)— fails in some browsers (see comment)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the [Polaris UI kit](https://polaris.shopify.com/resources/polaris-ui-kit)

### CODE REVIEW

**Comment by debchn** [comment]
Note — this solution is not supported by Safari, and other workarounds (`window.scrollTo` or setting `document.scrollTop`) similarly did not work on Safari 13 on my local machine.
The closest working solution I could find for Safari was:

```
    const {scrollX, scrollY} = window;

    panel.focus();

    setTimeout(() => {
      window.scrollTo(scrollX, scrollY);
    }, 0);
```

(There seems to be a race condition between `focus` and any preceding window scroll calls— see [this SO post](https://stackoverflow.com/questions/52652469/prevent-safari-from-automatically-scrolling-to-focused-element-scrollback-techn) for more details)

But, this would occasionally cause a visual flicker when changing between tabs 2 and 3 in the playground example (IMO worse UX than scrolling to a focused element).

All this is to say that I couldn't find a good working solution for Safari, but I hope that we could at least prevent scroll for the other supported browsers?

**Review by perrupa — APPROVED** [review]
I might get someone a bit more a11y savvy than myself to double-check, but this seems like a great solution to a really annoying bug. Really love how thorough you were in trying to find a Safari solution as well.

Great work!

**Review by tmlayton — APPROVED** [review]
Seems like a reasonable change. I don’t know of any a11y issues with the `preventScroll` option (/cc @dpersing). A quick Google search didn’t turn up much. And I do see that this option is passed through as part of Angular Material’s A11y API, so there’s that.

**Comment by dpersing** [comment]
Hi @tmlayton @debchn and @perrupa, sorry I didn't get a chance to look at this before it was merged.

This seems to work as I'd with the browser/AT combos I typically do a quick test with (although there is still a scroll-jump in Safari). I'm not able to test at the moment on mobile.

**Comment by lspoor** [comment]
Is this definitely working? Because every time I change tab my window scroll position is changing.

**Pull request merged**
