### PR TITLE
feat: Add Grid component

### PR DESCRIPTION
**Pull request by aaronccasanova**
### WHAT is this pull request doing?

This PR [re-introduces the `Grid` component](https://github.com/Shopify/polaris/pull/5748) and updates the implementation to use the JSON token groups in `polaris-react/src/tokens`.

### CODE REVIEW

**Review by laurkim — APPROVED** [review]
💯 

Tophatted using `polaris` snapshot in a spin instance and confirmed there weren't any errors re: breakpoints 👍

**Comment by aaronccasanova** [comment]
Wow thanks @laurkim! Will you review all my PRs ❤️

**Pull request merged**
