### PR TITLE
Create migration guidance for Sass global variables

### LINKED ISSUE #5006: Create migration guidance for Sass global variables

### PR DESCRIPTION
**Pull request by lgriffee**
### WHY are these changes introduced?

Fixes #5006

### WHAT is this pull request doing?

- Adding documentation for sass global variables (`$color-palette-data`, `$easing-data`, `$duration-data`) to our migration guide

<hr>

### Helpful References

- #4698
- #4699
- [polaris-tokens/dist/duration.map.scss](https://github.com/Shopify/polaris-tokens/blob/9cf5e0f2b478f3d008cba5618b479d26a27f3bf6/dist/duration.map.scss)
- [polaris-react/src/styles/foundation/_colors.scss](https://github.com/Shopify/polaris-react/blob/b07102c14a09aed8013a24d4fb5fd79ec9606164/src/styles/foundation/_colors.scss)
- [polaris-tokens/dist/colors.color-map.scss](https://github.com/Shopify/polaris-tokens/blob/main/dist/colors.color-map.scss)

### CODE REVIEW

**Review by aveline — APPROVED** [review]

**Comment by aaronccasanova** [comment]
Both vars are listed in the mega file. Wonder if we should just permalink there to save vertical space in this growing migration guide. Also, do you know why the names are different?
- `$color-palette-date` vs. [$polaris-colors](https://github.com/Shopify/polaris-react/blob/5267a30b845a0c07bec4036d723fb11c2cb24100/documentation/guides/legacy-polaris-v8-public-api.scss#L5-L88)
- `$duration-data` vs [$polaris-duration-map](https://github.com/Shopify/polaris-react/blob/5267a30b845a0c07bec4036d723fb11c2cb24100/documentation/guides/legacy-polaris-v8-public-api.scss#L243-L262)

**Comment by lgriffee** [comment]
> Both vars are listed in the mega file. Wonder if we should just permalink there to save vertical space in this growing migration guide. 

@aaronccasanova While `$easing-data` is listed directly in the mega file both `$color-palette-data` and `$duration-data` would require folks to take an extra step and look up the scss global variable that they equal (`$duration-data: $polaris-duration-map;`, `$color-palette-data: $polaris-colors;`). By writing them out here I was trying to take out that step and make it super easy for folks to copy and paste.

> Also, do you know why the names are different?
> 
> * `$color-palette-data` vs. [$polaris-colors](https://github.com/Shopify/polaris-react/blob/5267a30b845a0c07bec4036d723fb11c2cb24100/documentation/guides/legacy-polaris-v8-public-api.scss#L5-L88)
> * `$duration-data` vs [$polaris-duration-map](https://github.com/Shopify/polaris-react/blob/5267a30b845a0c07bec4036d723fb11c2cb24100/documentation/guides/legacy-polaris-v8-public-api.scss#L243-L262)

In the original file setup [polaris-react/src/styles/foundation/_duration.scss](https://github.com/Shopify/polaris-react/blob/51fc09b76f75b4b7e742a67912821443b9e15a3d/src/styles/foundation/_duration.scss) had an `@import '../polaris-tokens/duration.map';` which is where [`$polaris-duration-map`](https://github.com/Shopify/polaris-tokens/blob/9cf5e0f2b478f3d008cba5618b479d26a27f3bf6/dist/duration.map.scss) was located. And [polaris-react/src/styles/foundation/_colors.scss](https://github.com/Shopify/polaris-react/blob/b07102c14a09aed8013a24d4fb5fd79ec9606164/src/styles/foundation/_colors.scss) had an `@import '../polaris-tokens/colors.color-map';` which is where [`$polaris-colors`](https://github.com/Shopify/polaris-tokens/blob/9cf5e0f2b478f3d008cba5618b479d26a27f3bf6/dist/colors.color-map.scss) was located.

**Comment by aaronccasanova** [comment]
> both `$color-palette-data` and `$duration-data` would require folks to take an extra step and look up the scss global variable that they equal (`$duration-data: $polaris-duration-map;`, `$color-palette-data: $polaris-colors;`).

Understood 👍  Could we list both variables like the other reference tables, for example:
| Variable | Replacement|
|-|-|
|`$duration-data`<br/>`$polaris-duration-map`|[definition](https://github.com/Shopify/polaris-react/blob/5267a30b845a0c07bec4036d723fb11c2cb24100/documentation/guides/legacy-polaris-v8-public-api.scss#L244-L261)|

Import to note this is non-blocking! Just looking for any opportunity to tidy up and consolidate this guide.

**Comment by lgriffee** [comment]
> | Variable | Replacement|
> |-|-|
> |`$duration-data`<br/>`$polaris-duration-map`|[definition](https://github.com/Shopify/polaris-react/blob/5267a30b845a0c07bec4036d723fb11c2cb24100/documentation/guides/legacy-polaris-v8-public-api.scss#L244-L261)|

@aaronccasanova Great suggestion! I love this idea!

**Pull request merged**
