### PR TITLE
Add as="div" option to Text component

### PR DESCRIPTION
**Pull request by nikk-ca**
### WHY are these changes introduced?

Enables the usage of the Text component for styling a section of text (consisting of multiple paragraphs).

```diff
- <div>
-   <Text variant="bodySm" color="subdued" as="p">Lorem</Text>
-   <Text variant="bodySm" color="subdued" as="p">ipsum</Text>
-   <Text variant="bodySm" color="subdued" as="p">dolor</Text>
- </div>

+ <Text variant="bodySm" color="subdued" as="div">
+   <p>Lorem</p>
+   <p>ipsum</p>
+   <p>dolor</p>
+ </Text>
```

### CODE REVIEW

**Comment by yurm04** [comment]
This feels like a use case that maybe was not considered in the `Text` API and I wonder if it goes against the intended use of the component 🤔 tagging @laurkim and @aveline to see if they have context they can provide.

In general, I have some concerns with accessibility since allowing `div` means you can have non-semantic text and that can make it hard for screen readers to announce the hierarchy/structure of the text

```
<Text as='div' variant='headingLg'>A screen reader won't announce this with a helpful semantic HTML element</Text>
```

**Review by kyledurand — CHANGES_REQUESTED** [review]
As @yurm04 said this isn't great for readers and div isn't a good semantic for flow content

You should just do:
```tsx
<Text as="p" variant="heading2xl">
  <Text as="p">This is heading2xl</Text>
  <Text as="p">This also heading2xl</Text>
</Text>
```

**Comment by nikk-ca** [comment]
This is to allow it to be used as a styling container for semantic elements, not instead of them. A common use case would be to make a group of text content `subdued` without needing to create a CSS class for it. @kyledurand, your example is what I'm trying to do, but it's not valid HTML, as a `<p>` can't contain flow content (i.e., another `<p>`).

**Comment by kyledurand** [comment]
> `<p> can't contain flow content (i.e., another <p>`

If this is true then this is a limitation that we should address with the Text component by adding either more semantic options for flow content, or more options for phrasing content. 

I made the example quickly and storybook didn't flag any a11y issues for nesting paragraphs so I'm surprised that it's not valid. That said, it really doesn't make sense to nest paragraphs and we can make improvements here.

Can you give more context as to what you need to do? That might help us add the proper, semantic, elements here

**Comment by kyledurand** [comment]
Alternatively you could use spans and stack:

```jsx
<Text as="p" variant="heading2xl">
  <AlphaStack>
    <Text as="span">This is heading2xl</Text>
    <Text as="span">This also heading2xl</Text>
  </AlphaStack>
</Text>
```

**Comment by nikk-ca** [comment]
As an example, in [this PR](https://github.com/Shopify/web/pull/86348), I'm just using a couple of utility classes to make all the text small and subdued inside of each "Terms" card section.

**Comment by nikk-ca** [comment]
> Alternatively you could use spans and stack:
> 
> ```js
> <Text as="p" variant="heading2xl">
>   <AlphaStack>
>     <Text as="span">This is heading2xl</Text>
>     <Text as="span">This also heading2xl</Text>
>   </AlphaStack>
> </Text>
> ```

From an accessibility standpoint, this would read as a single paragraph though — "This is heading2xl This also heading2xl".

The idea of adding `div` is that there are often cases where we could benefit from being able to style an entire section of content *without* changing the content structure.

**Comment by itwasmattgregg** [comment]
Could we possibly allow for some text styling on `Box` that `Text` could inherit?

**Comment by chloerice** [comment]
> Could we possibly allow for some text styling on `Box` that `Text` could inherit?

`Box` does [support](https://codesandbox.io/s/text-inheriting-box-color-style-m1woyr) `color`, but currently doesn't support any other font declaration props.

```tsx
<Box color="text-subdued">
  <Text variant="bodySm" as="p">Lorem</Text>
  <Text variant="bodySm" as="p">ipsum</Text>
  <Text variant="bodySm" as="p">dolor</Text>
</Box>
```

**Comment by kyledurand** [comment]
> Could we possibly allow for some text styling on Box that Text could inherit?

If we could do that without duplicating a bunch of the css from the text component I would be all for it

**Comment by itwasmattgregg** [comment]
> `Box` does [support](https://codesandbox.io/s/text-inheriting-box-color-style-m1woyr) `color`, but currently doesn't support any other font declaration props.

This is not a bad middle ground.

**Comment by chloerice** [comment]
Here's an example of an inheritance [combo](https://codesandbox.io/s/text-inheriting-variant-style-ypyhik?file=/App.tsx) if you're feeling wild 😀

**Comment by nikk-ca** [comment]
> Here's an example of an inheritance [combo](https://codesandbox.io/s/text-inheriting-variant-style-ypyhik?file=/App.tsx) if you're feeling wild 😀

Same issue as [this one](https://github.com/Shopify/polaris/pull/8698#pullrequestreview-1346447589) though. You're not supposed to put `<p>` inside of a `<span>`.

**Comment by chloerice** [comment]
> > Here's an example of an inheritance [combo](https://codesandbox.io/s/text-inheriting-variant-style-ypyhik?file=/App.tsx) if you're feeling wild 😀
> 
> Same issue as [this one](https://github.com/Shopify/polaris/pull/8698#pullrequestreview-1346447589) though. You're not supposed to put `<p>` inside of a `<span>`.

Ugh that's right 😣 

I'm not opposed to `as="div"`since it prevents the redundant CSS that would need to be added to Box, but also understand the desire for strong separation of concerns. :notsure: :thunk:

One thing I do in similar situations when rendering several components with the same or similar props is set the redundant props on an object variable and spread them onto the components.

**Comment by aveline** [comment]
Lots of great discussion and points in this thread.

> One thing I do in similar situations when rendering several components with the same or similar props is set the redundant props on an object variable and spread them onto the components.

I think considering those types of approaches is the way to go to avoid the repetitiveness of having to set the props individually on each `Text` instance.

> This is to allow it to be used as a styling container for semantic elements, not instead of them.

As @chloerice mentioned, we want to keep separation of concerns and introducing containers intending to affect styles starts to muddle this.

`Text` is intended to be a semantic element. Introducing `div` dilutes this and the downside is not worth the upside of saving a bit of repetition when there are other ways to solve for that without affecting semantics.

**Pull request closed without merging**
