### PR TITLE
docs: Update legacy file with replacement tokens

### PR DESCRIPTION
**Pull request by aaronccasanova**
### WHAT is this pull request doing?

This PR adjusts the `legacy-polaris-v8-public-api.scss` file by replacing legacy custom properties with their updated values.

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
- [ ] For visual design changes, ping @ sarahill to update the Polaris UI kit

### CODE REVIEW

**Review by lgriffee — APPROVED** [review]
🎉🚢✨💯

**Review by sam-b-rose — APPROVED** [review]
Nice catch! Get those invalid import outta here 👍

**Comment by BPScott** [comment]
Is the content of those imports that have been removed present in the file? I'm seeing usage of $polaris-colors / $polaris-spacing variables but I'm not seeing where those variables are defined. I suspect that because we've got weird hangover `@import` declarations, the contents of those files were never included in legacy-polaris-v8-public-api.scss.

For instance:


- $polaris-spacing, came from [spacing.spacing-map.scss](https://unpkg.com/browse/@shopify/polaris@8.2.2/build/styles/polaris-tokens/spacing.spacing-map.scss)
- $polaris-colors came from [colors.colors-map.scss](https://unpkg.com/browse/@shopify/polaris@8.2.2/build/styles/polaris-tokens/colors.color-map.scss)

**Comment by sam-b-rose** [comment]
> Is the content of those imports that have been removed present in the file?

Looks like the `colors`, `color-filters`, `spacing`, and `duration` maps are [defined towards the top](https://github.com/Shopify/polaris-react/blob/ba4212fc4035828caf53fa1a49fbdbc57518b794/documentation/guides/legacy-polaris-v8-public-api.scss#L266) of the file.

Does seem to be defined a bit far away from the usage in some cases like spacing, but that is the organizational challenge of a 1000+ line mega file I suppose 😅

**Comment by aaronccasanova** [comment]
> Is the content of those imports that have been removed present in the file?

Yes, the script I created to generate the mega file was refined/executed multiple times and thus I placed the import contents at the top to make transferring them a quick copy/paste.

**Review by aveline — APPROVED** [review]

**Pull request merged**
