### PR TITLE
Improve density of various elements

### PR DESCRIPTION
**Pull request by martenbjork**
Increases the density of various elements Polaris elements.

increase-action-list-density (4)

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by kyledurand — APPROVED** [review]
Chromatic changes look good to me 👍

**Comment by heyjoethomas** [comment]
Only thing I am seeing is the horizontal padding on the action list now has the icon running into the edge of the container on hover.
**Prod**
Screenshot 2023-05-11 at 9 44 41 AM
**Spin**
Screenshot 2023-05-11 at 9 43 16 AM

**Comment by martenbjork** [comment]
> Only thing I am seeing is the horizontal padding on the action list now has the icon running into the edge of the container on hover. **Prod** Screenshot 2023-05-11 at 9 44 41 AM **Spin** Screenshot 2023-05-11 at 9 43 16 AM

Oof, good catch! Is this the home card `...` menu?

**Pull request closed without merging**
