### PR TITLE
[Filters] Add support for indicating an applied filter has unsaved changes

### PR DESCRIPTION
**Pull request by chloerice**
### WHY are these changes introduced?

Part of https://github.com/Shopify/web/issues/76490

### WHAT is this pull request doing?

Adds support for indicating unsaved changes have been made to the applied filters.

Screenshot 2024-04-04 at 4 26 23 PM

### How to 🎩
📚 [Storybook](https://5d559397bae39100201eedc1-fbscsztkor.chromatic.com/?path=/story/all-components-filters--with-children-content-and-unsaved-changes)
🌀 [Spinstance](https://admin.web.unsaved-indexfilter-changes.chloe-rice.us.spin.dev/store/shop1/products?selectedView=all&status=ACTIVE)

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [x] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by mrcthms — APPROVED** [review]
Love it, behaving exactly as I would expect!

**Review by kyledurand — APPROVED** [review]
LGTM 👍

**Review by laurkim — APPROVED** [review]
Nice 💯

**Review by davidlng — APPROVED** [review]

**Review by sarahill — APPROVED** [review]
✅

**Pull request merged**
