### PR TITLE
Add support for tooltips in Navigation section items

### LINKED ISSUE #5752: Add support for tooltips on navigation item action buttons
## Feature request summary
Add a `tooltip` property to the navigation section item component and secondary action so you can show tooltips that explain what the action button/secondary action does. 

**FYI, I am in the process of implementing a proposed version of this for Shopify hack days**

## Rationale
Our Navigation.Section component and section item component both have an "action" or "secondary action", letting you add a button with an icon. The problem is that if the button's function is not self-explanatory, there is no way to show a tooltip. Ironically, we support accessibility labels but these are not visible to ordinary users.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

### PR DESCRIPTION
**Pull request by stewx**
### WHY are these changes introduced?
Our Navigation.Section component and section item component both have an "action" or "secondary action", letting you add a button with an icon. The problem is that if the button's function is not self-explanatory, there is no way to show a tooltip. Ironically, we support accessibility labels but these are not visible to ordinary users.

Resolves #5752 
Resolves Shopify/polaris-styleguide/#5778

In terms of value to Shopify, this unlocks additional value in our admin UI because we have buttons that could really use informative tooltips.

### WHAT is this pull request doing?

1. Add an optional `tooltip` property in each of these components, making use of the existing Tooltip component.
2. Update tests
3. Update Storybook playground to include examples of using tooltip
4. Update documentation to include new property
5. Add documentation for SubNavigationItem and SecondaryAction
6. Fix some inaccurate documentation

### Demo video
In this demo, the first two buttons have a tooltip attached, while the third does not.

https://user-images.githubusercontent.com/6986171/167639531-c722636d-2ab4-4ab4-9c19-a61592a42cd5.mp4

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide
- [ ] For visual design changes, ping @ sarahill to update the Polaris UI kit

### CODE REVIEW

**Comment by ghost** [comment]
👋 Thanks for opening your first pull request. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by stewx** [comment]
I'm not sure if this qualifies as a visual change, @sarahill

**Review by sam-b-rose — COMMENTED** [review]
This looks excellent, very nice addition! Thank you for making this contribution @stewx 💯 

Everything checks out to me, would still like one more opinion (@alex-page or @martenbjork). 

Only request I have would be to add a Feature entry to the `UNRELEASED.md` to be appended to the `CHANGELOG.md` on next release. 👍

**Comment by stewx** [comment]
> This looks excellent, very nice addition! Thank you for making this contribution @stewx 💯
> 
> Everything checks out to me, would still like one more opinion (@alex-page or @martenbjork).
> 
> Only request I have would be to add a Feature entry to the `UNRELEASED.md` to be appended to the `CHANGELOG.md` on next release. 👍

@samrose3 Done.

**Review by sam-b-rose — APPROVED** [review]

**Review by alex-page — APPROVED** [review]

**Comment by ghost** [comment]
🎉 Thanks for your contribution to Polaris!

**Pull request merged**
