### PR TITLE
[WIP] [SettingToggle] Update documentation

### PR DESCRIPTION
**Pull request by heydouble-a**
### WHY are these changes introduced?

In conjunction with:

- [React component PR](https://github.com/Shopify/polaris/issues/8328)
- [Figma UI Kit branch](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/branch/880uUKf3RpIwVO5Xdztqou/Polaris-Components?node-id=2098%3A51&t=1D6OBgTNb2P4gCR3-1) 

### WHAT is this pull request doing?
Updating Polaris documentation on changes to the setting toggle design. 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Comment by oluwatimio** [comment]
@deannatron @heydouble-a I added the documentation updates from this PR to https://github.com/Shopify/polaris/pull/8547 where the component implementation is so we can most likely close this one. What do we think?

Also do we need to update the checkbox docs like this PR is doing?

**Comment by heydouble-a** [comment]
> 

We do need to make sure the checkbox documentation is updated. JJ was able to make those changes here.

**Comment by heydouble-a** [comment]
@ouellettejordan take a look at the [commits](https://github.com/Shopify/polaris/pull/8497/commits) for the [updated markdown for the setting toggle](https://github.com/Shopify/polaris/pull/8497/commits/cfdf0d50bd5e9ed3623a98df7b1a8055f6206079?short_path=c318fd6#diff-c318fd6fc438eb9e0c4db6bcf0638389f93a7b355983971b471712f561bf8d92). You'll see how we've explained when this would be a good component to use, language guidelines, etc. (No decision tree diagrams here.)

Any feedback is appreciated!

**Comment by oluwatimio** [comment]
This PR was replaced by https://github.com/Shopify/polaris/pull/8547 so closing this

**Pull request closed without merging**
