### PR TITLE
[Page] prevent vertical content shift of header with metadata and actions

### PR DESCRIPTION
**Pull request by mattkubej**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/web/issues/103405

Inconsistent Header height within the `Page` component is leading to the Header shifting vertically when navigating between pages with different properties enabled (e.g. metadata, actions). This pull request makes adjustments to combat the shifting.

### WHAT is this pull request doing?

- Consistent Header row height of 28px
   - Header Title will always have 2px of vertical padding to bring the 24px line height to 28px in total for the container
   - Allow for bleeding of the Title metadata, so metadata can be larger than Title without impacting alignment (e.g. Location picker)
- Removes vertical alignment and margin-top of Title metadata, which had no impact to aesthetic
- Reorganizes CSS to make class/style relationships clearer
- Adds new Storybook to highlight problem

NOTE: This is a bit of a bandaid fix. We should likely rewrite this component to utilize a grid layout to have a more resilient solution for achieving the desired aesthetic, but considering the variability in configurations of this component that is a sizable effort. However, I think we'd need to understand the desired aesthetic when a subtitle exists along with title metadata content that is larger than the title to determine the optimal solution. 

### How to 🎩

[Spin - Web](https://admin.web.fix-page-header-shift.matt-kubej.us.spin.dev/store/shop1/orders?inContextTimeframe=none)
[Spin - Polaris Storybook](https://storybook.web.fix-page-header-shift.matt-kubej.us.spin.dev/?path=/story/all-components-page--with-metadata-and-badge-and-action&globals=polarisSummerEditions2023:true;polarisSummerEditions2023ShadowBevelOptOut:true)

Validate when navigating amongst root pages (e.g. draft orders, products) that the Page Header does not shift with/without the presence of title metadata and actions. Also, validate that the Header row has contents vertically centered.

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by mrcthms — APPROVED** [review]
Looks good, nice work!

**Review by sam-b-rose — APPROVED** [review]
🎩  looks good! Can we target the `12.x.x` branch? We are tee'ing up the next major release this week and v12 is likely the next version be be shipped.

Also fine with having this fix in `main` but we'll also want to resolve any conflicts and ensure these changes are properly carried over to `12.x.x`

**Review by ouellettejordan — APPROVED** [review]
Tested spin link and looks good to me 👍

**Review by sarahill — APPROVED** [review]

**Comment by mattkubej** [comment]
> 🎩 looks good! Can we target the 12.x.x branch? We are tee'ing up the next major release this week and v12 is likely the next version be be shipped.

Yea, I can do that, but I won't be able to get to that until this evening if that's alright @sam-b-rose

**Comment by mattkubej** [comment]
Closing in favor of https://github.com/Shopify/polaris/pull/11168 due to the v12 changes

**Pull request closed without merging**
