### PR TITLE
[Text] Add `disabled` support to `color` prop on Text component

### PR DESCRIPTION
**Pull request by peylun**
### WHY are these changes introduced?

Re: https://github.com/Shopify/shopify-audiences/issues/8615, https://github.com/Shopify/shopify-audiences/pull/9728

To support the case where Text needs to be rendered on an onboarding step card that is disabled, and needs to be rendered in disabled color:
image

### WHAT is this pull request doing?

- Added `disabled` type to `color` prop on `Text` component
- Added `.disabled` css to so that `color=disabled` would add the corresponding class name to the component with `color: var(--p-color-text-subdued)`
- Added `color=disabled` to the story `WithColor`; added color type prefix to each paragraph to better indicate the color type for each example

image

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by kyledurand — CHANGES_REQUESTED** [review]
I'd like to get some eyes from UX on this before it ships. 

You'll also need to fix the failing contrast check. You could to do something like `{...(disabled && {'aria-disabled': true})}` on the text node, but this is only a possible solution and not necessarily the best one because the text is still very hard to read

**Comment by tjonx** [comment]
Does this text need to be readable by the user in the given circumstances? `disabled` elements are equivalent to being completely invisible for all users, including screen readers. If we're expecting the user to be able to read `disabled` elements then they should have a `read-only` style instead.

**Comment by peylun** [comment]
Thanks @kyledurand and @tjonx for highlighting accessibility issues which I have missed.

For context, this is used in our app onboarding page to set up external platform accounts on disabled setup step card when pre-requisites were not met:

image

> Does this text need to be readable by the user in the given circumstances? disabled elements are equivalent to being completely invisible for all users, including screen readers.

Probably meant to de-focus them on the disabled cards but focus on the enabled / expanded cards. Noted on the (non-)readability and will relay this to our UX designers. cc @elliekllr 

> If we're expecting the user to be able to read disabled elements then they should have a read-only style instead.

Is this an available style that I could use or are you suggesting a different style meant for read-only?

**Comment by elliekllr** [comment]
There isn't an official "read only" text colour. Let's use text-subdued instead to address accessibility. Thanks for raising it! I've update the figma to reflect this change @peylun

**Comment by peylun** [comment]
> There isn't an official "read only" text colour. Let's use text-subdued instead to address accessibility. Thanks for raising it! I've update the figma to reflect this change @peylun

Thanks @elliekllr !

Thanks @kyledurand @tjonx! Will close this PR 🙇

**Pull request closed without merging**
